import { test, expect } from '@playwright/test';
import { loginAs, adminEmail, customerEmail, uid } from './accounts';

test('dealer captures a mobile lead and adds stock without importing for a retail buyer', async ({ page }) => {
  test.setTimeout(180000);
  await page.setViewportSize({width:390,height:900});
  await loginAs(page,adminEmail);
  await expect(page).toHaveURL(/\/app$/);
  await page.goto('/app/dealership');
  await expect(page.getByRole('heading',{name:'Dealership',exact:true})).toBeVisible();
  const name = `Buyer ${uid()}`;
  await page.getByLabel('Customer name',{exact:true}).fill(name);
  await page.getByLabel('WhatsApp / phone').fill('+263771234567');
  await page.getByLabel('Budget (USD)').fill('8500');
  await page.getByLabel('Vehicle preferences').fill('Toyota Aqua, local stock or Japan import');
  await page.getByRole('button',{name:'Save enquiry'}).click();
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
  await page.getByLabel(`Status for ${name}`).selectOption('contacted');
  await expect(page.getByLabel(`Status for ${name}`)).toHaveValue('contacted');
  await page.screenshot({path:'release-evidence/dealership-leads-mobile.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Stock',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Add a registered vehicle to stock'})).toBeVisible();
  await page.getByRole('button',{name:'Sales',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Reserve a vehicle'})).toBeVisible();
  await page.setViewportSize({width:1440,height:900});
  await page.screenshot({path:'release-evidence/dealership-sales-desktop.png',fullPage:true});
  await page.goto('/app/new/vehicle');
  const chassis = `NHP10-${Date.now().toString().slice(-7)}`;
  await page.getByPlaceholder('e.g. JN1CMAT51A0004100').fill(chassis);
  await page.getByPlaceholder('Toyota',{exact:true}).fill('Toyota');
  await page.getByPlaceholder('Corolla',{exact:true}).fill('Aqua');
  await page.getByPlaceholder('2019',{exact:true}).fill('2020');
  await page.getByRole('button',{name:'Register vehicle',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Vehicle registered'})).toBeVisible();
  await page.getByRole('button',{name:'Add this vehicle to dealer stock'}).click();
  await page.getByRole('button',{name:'Stock',exact:true}).click();
  await page.getByLabel('Stock vehicle').selectOption({label:`2020 Toyota Aqua · ${chassis}`});
  await page.getByLabel('Vehicle location').fill('Harare');
  await page.getByLabel('Asking price (USD)').fill('8000');
  await page.getByLabel('Acquisition / owner settlement cost (USD)').fill('5000');
  await page.getByLabel('Other direct costs (USD)').fill('1000');
  await page.getByRole('button',{name:'Add stock',exact:true}).click();
  await expect(page.getByRole('heading',{name:'2020 Toyota Aqua',exact:true})).toBeVisible();
  await page.getByLabel(/^Upload photos for /).setInputFiles({name:'test-vehicle.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPZ8AAAAASUVORK5CYII=','base64')});
  await expect(page.getByText('Cover photo',{exact:true})).toBeVisible();
  const photoUrl=await page.getByRole('img',{name:'Vehicle photo 1',exact:true}).getAttribute('src');
  expect(photoUrl).toBeTruthy();expect((await page.request.get(photoUrl!)).status()).toBe(200);
  const privatePhotoUrl=new URL(photoUrl!);privatePhotoUrl.searchParams.delete('token');
  expect((await page.request.get(privatePhotoUrl.toString())).status()).toBe(403);
  await page.getByLabel('Published mileageKm',{exact:true}).fill('45000');
  await page.getByLabel('Published fuel',{exact:true}).selectOption('Hybrid');
  await page.getByLabel('Published transmission',{exact:true}).selectOption('Automatic');
  await page.getByLabel('Description for 2020 Toyota Aqua').fill('Duty paid local stock. View in Harare.');
  await page.getByLabel('Publish available stock').check();
  await page.getByRole('button',{name:'Save showroom listing'}).click();
  await expect(page.getByRole('button',{name:'Save showroom listing'})).toBeEnabled();
  const showroom = await page.context().newPage();
  await showroom.goto('/showroom/e2e');
  await expect(showroom.getByRole('heading',{name:'2020 Toyota Aqua',exact:true})).toBeVisible();
  await showroom.getByRole('link',{name:'View vehicle & enquire about 2020 Toyota Aqua'}).click();
  await expect(showroom.getByText('45,000 km',{exact:true})).toBeVisible();
  await showroom.getByLabel('Your name').fill('Public visitor');
  await showroom.getByLabel('WhatsApp / phone').fill('+263771111111');
  await showroom.getByLabel('Vehicle and budget').fill('Aqua local stock');
  await showroom.getByRole('button',{name:'Send enquiry'}).click();
  await expect(showroom.getByRole('status').filter({hasText:'Your enquiry has reached'})).toContainText('Your enquiry has reached');
  await showroom.screenshot({path:'release-evidence/dealership-showroom-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Sales',exact:true}).click();
  await page.getByLabel('Available vehicle').selectOption({label:'2020 Toyota Aqua · $8,000.00'});
  await page.getByLabel('Buyer',{exact:true}).selectOption({label:'Test Customer'});
  await page.getByLabel('Agreed price (USD)').fill('8000');
  await page.getByLabel('Reservation expires').fill('2027-01-01T12:00');
  await page.getByLabel('Agreed sale terms').fill('Full payment before signed handover');
  await page.getByRole('button',{name:'Reserve vehicle',exact:true}).click();
  await expect(page.getByText('Price $8,000.00 · Received $0.00 · Balance $8,000.00',{exact:true})).toBeVisible();
  await page.getByLabel('Amount (USD, for payment/refund)').fill('8000');
  await page.getByLabel('Transaction evidence').fill('Confirmed bank transfer BANK-123');
  await page.getByRole('button',{name:'Record action'}).click();
  await expect(page.getByText('Price $8,000.00 · Received $8,000.00 · Balance $0.00',{exact:true})).toBeVisible();
  await page.locator('select[name="action"]').selectOption('handover');
  await page.getByLabel('Transaction evidence').fill('Buyer signed handover acknowledgement H-123');
  await page.getByRole('button',{name:'Record action'}).click();
  await expect(page.getByRole('button',{name:'Record action'})).toHaveCount(0);
  await page.getByRole('link',{name:'Purchase details and documents'}).click();
  await expect(page.getByRole('heading',{name:'Issue sales documents'})).toBeVisible();
  const purchaseUrl=page.url();
  await page.getByRole('button',{name:'Issue sale agreement'}).click();
  await expect(page.getByRole('heading',{name:'Vehicle sale agreement'})).toBeVisible();
  await expect(page.getByText(`VIN / chassis: ${chassis}`,{exact:true}).last()).toBeVisible();
  await page.screenshot({path:'release-evidence/retail-sale-agreement-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Close document'}).click();
  await page.getByRole('button',{name:'Issue payment receipt'}).click();
  await expect(page.getByRole('heading',{name:'Payment receipt',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close document'}).click();
  await page.getByRole('button',{name:'Issue handover record'}).click();
  await expect(page.getByRole('heading',{name:'Vehicle handover record'})).toBeVisible();
  await page.getByRole('button',{name:'Close document'}).click();
  const buyerContext=await page.context().browser()!.newContext({viewport:{width:390,height:844}});const buyerPage=await buyerContext.newPage();
  await loginAs(buyerPage,customerEmail);await expect(buyerPage).toHaveURL(/\/app$/);
  await buyerPage.goto(purchaseUrl);await expect(buyerPage.getByText('Vehicle handover completed',{exact:true})).toBeVisible();
  await expect(buyerPage.getByRole('heading',{name:'Issue sales documents'})).toHaveCount(0);
  await expect(buyerPage.getByText('Owner cost and price controls')).toHaveCount(0);
  await buyerPage.screenshot({path:'release-evidence/retail-purchase-customer-mobile.png',fullPage:true});
  expect(await buyerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await buyerPage.setViewportSize({width:320,height:740});expect(await buyerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await buyerContext.close();
  await showroom.reload();
  await expect(showroom.getByRole('heading',{name:'2020 Toyota Aqua',exact:true})).toHaveCount(0);
  await showroom.close();
});

test('enquiry converts into a customer import without entering the customer twice',async({page})=>{
  await page.setViewportSize({width:390,height:844});await loginAs(page,adminEmail);await expect(page).toHaveURL(/\/app$/);await page.goto('/app/dealership');
  const name=`Import buyer ${uid()}`;await page.getByLabel('Customer name',{exact:true}).fill(name);await page.getByLabel('WhatsApp / phone').fill('+263771234569');await page.getByLabel('Looking for').selectOption('import');await page.getByRole('button',{name:'Save enquiry'}).click();
  const card=page.locator('.card').filter({has:page.getByRole('heading',{name,exact:true})});await expect(card).toBeVisible();await card.getByLabel(`Journey for ${name}`).selectOption('import');await card.getByRole('button',{name:'Continue enquiry'}).click();
  await expect(page.getByRole('heading',{name:'New import case',exact:true})).toBeVisible();await expect(page.locator('form select').first()).toContainText(name);await expect(page.locator('form select').first().locator('option:checked')).toContainText(name);
  await page.getByRole('button',{name:'Create import',exact:true}).click();await expect(page.getByRole('heading',{name:'Import case created'})).toBeVisible();
});

test('dealer imports for its own stock and transfers actual landing costs after preparation',async({page})=>{
  test.setTimeout(180000);await page.setViewportSize({width:390,height:844});await loginAs(page,adminEmail);await expect(page).toHaveURL(/\/app$/);
  await page.goto('/app/new/vehicle');const chassis=`NCP91-${Date.now().toString().slice(-7)}`;await page.getByPlaceholder('e.g. JN1CMAT51A0004100').fill(chassis);await page.getByPlaceholder('Toyota',{exact:true}).fill('Toyota');await page.getByPlaceholder('Corolla',{exact:true}).fill('Vitz');await page.getByPlaceholder('2019',{exact:true}).fill('2018');await page.getByRole('button',{name:'Register vehicle',exact:true}).click();await expect(page.getByRole('heading',{name:'Vehicle registered'})).toBeVisible();
  await page.goto('/app/acquisitions');await page.getByLabel('Acquisition vehicle').selectOption({label:`2018 Toyota Vitz · ${chassis}`});await page.getByLabel('Acquisition supplier',{exact:true}).fill('BE FORWARD');await page.getByLabel('Supplier acquisition reference').fill(`BF-${uid()}`);await page.getByRole('button',{name:'Start acquisition'}).click();
  await expect(page.getByRole('heading',{name:'2018 Toyota Vitz',exact:true})).toBeVisible();await page.getByLabel('Cost amount for 2018 Toyota Vitz').fill('3000');await page.getByLabel('Cost evidence for 2018 Toyota Vitz').fill('Dealer paid supplier invoice BF-001');await page.getByRole('button',{name:'Record actual cost'}).click();await expect(page.getByText('Purchase $3,000.00 · Landing/preparation $0.00 · Recorded cost $3,000.00',{exact:true})).toBeVisible();
  await page.getByLabel('Cost category for 2018 Toyota Vitz').selectOption('freight');await page.getByLabel('Cost amount for 2018 Toyota Vitz').fill('1000');await page.getByLabel('Cost evidence for 2018 Toyota Vitz').fill('Freight invoice F-001');await page.getByRole('button',{name:'Record actual cost'}).click();await expect(page.getByText('Purchase $3,000.00 · Landing/preparation $1,000.00 · Recorded cost $4,000.00',{exact:true})).toBeVisible();
  for(const stage of ['purchased','shipped','arrived','cleared','prepared']){await page.getByLabel('Stage evidence for 2018 Toyota Vitz').fill(`Confirmed ${stage}`);await page.getByRole('button',{name:`Advance to ${stage}`,exact:true}).click();await expect(page.getByText(`Stage: ${stage}`,{exact:true})).toBeVisible();}
  await page.getByLabel('Stock location for 2018 Toyota Vitz').fill('Harare');await page.getByLabel('Stock asking price for 2018 Toyota Vitz').fill('6000');await page.getByLabel('Transfer evidence for 2018 Toyota Vitz').fill('Clearance and preparation completed');await page.getByLabel('All actual acquisition costs are recorded').check();await page.getByRole('button',{name:'Transfer into available stock'}).click();await expect(page.getByText('Stage: stocked',{exact:true})).toBeVisible();await page.screenshot({path:'release-evidence/dealer-acquisition-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto('/app/dealership');await page.getByRole('button',{name:'Stock',exact:true}).click();await expect(page.getByRole('heading',{name:'2018 Toyota Vitz',exact:true})).toBeVisible();
});
