import { test, expect } from '@playwright/test';
import { loginAs, adminEmail, customerEmail, uid } from './accounts';

test('quotation acceptance, printable receipt and an audited reversal complete the client finance journey', async ({ browser }) => {
  test.setTimeout(180_000);
  const ownerContext = await browser.newContext(); const owner = await ownerContext.newPage();
  await loginAs(owner, adminEmail); await expect(owner).toHaveURL(/\/app$/);
  await owner.getByText('E20001').first().click(); const caseUrl = owner.url();
  await owner.getByRole('button',{name:'Set next action',exact:true}).click();
  await owner.getByLabel('Action needed',{exact:true}).fill('Upload supplier invoice');
  await owner.getByLabel('Who needs to act?',{exact:true}).selectOption('customer');
  await owner.getByRole('button',{name:'Save next action',exact:true}).click();
  await expect(owner.getByText('Action needed from the customer',{exact:true})).toBeVisible();
  await owner.getByLabel('Quote route',{exact:true}).fill('Durban to Harare');
  await owner.getByLabel('Quote inclusions',{exact:true}).fill('Delivery and agency service fee as itemised');
  await owner.getByLabel('Quote exclusions',{exact:true}).fill('Vehicle registration');
  await owner.getByLabel('Quote valid until',{exact:true}).fill(new Date(Date.now()+86400000).toISOString().slice(0,10));
  await owner.getByRole('button', { name: 'Re-issue quotation' }).click();
  await expect(owner.getByText(/Quotation v\d+ issued:/)).toBeVisible();
  await expect(owner.getByRole('button', { name: 'Print quotation / save PDF' })).toBeVisible();
  const customerContext = await browser.newContext(); const customer = await customerContext.newPage();
  await loginAs(customer, customerEmail); await expect(customer).toHaveURL(/\/app$/); await customer.goto(caseUrl);
  await expect(customer.getByText('Upload supplier invoice',{exact:true})).toBeVisible();
  await expect(customer.getByText(/Exclusions:.*Vehicle registration/)).toBeVisible();
  await customer.getByRole('button', { name: 'Accept this quotation' }).click();
  await expect(customer.getByText('Quotation accepted.')).toBeVisible();
  await customer.getByRole('button', { name: 'Print quotation / save PDF' }).click();
  await expect(customer.getByText('Quotation reference:')).toBeVisible();
  await expect(customer.locator('.print-sheet').getByText('Route: Durban to Harare',{exact:true})).toBeVisible();
  await customer.emulateMedia({ media: 'print' });
  await customer.screenshot({ path: 'test-results/quotation-print.png', fullPage: true });
  await customer.emulateMedia({ media: 'screen' }); await customer.getByRole('button', { name: 'Close document' }).click();
  await owner.reload();
  const reference = `FIN-${uid()}`;
  await owner.getByPlaceholder('150.00').fill('100'); await owner.getByPlaceholder('ECO123').fill(reference);
  await owner.getByRole('button', { name: 'Record payment' }).click();
  await expect(owner.getByText('Payment recorded as pending')).toBeVisible();
  const row = owner.locator('div.card').filter({ has: owner.getByText(`Ref: ${reference}`, { exact: true }) });
  await row.getByRole('button', { name: 'Confirm payment' }).click(); await expect(row.getByText('confirmed', { exact: true })).toBeVisible();
  await owner.getByRole('button', { name: new RegExp(`Receipt ${reference}`) }).click();
  await expect(owner.getByRole('heading', { name: 'Payment receipt' })).toBeVisible();
  await owner.getByRole('button', { name: 'Close document' }).click();
  await row.getByRole('button', { name: 'Correct this payment' }).click();
  await row.getByLabel('Correction reason').fill('Test receipt entered on the wrong case');
  await row.getByLabel('Correction reference').fill(`CORR-${reference}`);
  await row.getByRole('button', { name: 'Record correction' }).click();
  await expect(row.getByText('reversed', { exact: true })).toBeVisible();
  await expect(owner.getByRole('button', { name: new RegExp(`Receipt ${reference}`) })).toHaveCount(0);
  await customerContext.close(); await ownerContext.close();
});
