import { test, expect } from '@playwright/test';
import { beforwardSeed } from '../../firebase/functions/src/beforwardSeed';
const vehicle={...beforwardSeed[0],checkedAt:new Date().toISOString()};
const estimate={lowCents:780000,highCents:960000,taxesCents:221400,dutyCents:140000,surtaxCents:60000,vatCents:19400,carbonTaxCents:600,outsideCents:[90000,160000],deliveryCents:[120000,250000],agencyFeeCents:[30000,75000],dutyPct:40,vatPct:15.5,surtaxPct:35,surtaxApplied:true,vehicleAgeYears:6,ageAssumed:false,tooOld:false,category:'sedan_station_wagon',categoryAssumed:false,body:'Hatchback',asAt:'2026-10-09'};
test('buyer selects supplier vehicle and dealer; enquiry carries reference and remains inside Radbit',async({page})=>{
 await page.route('**/publicSupplierCatalogue',r=>r.fulfill({json:{result:{stock:[{...vehicle,estimate}],limited:true}}}));
 await page.route('**/publicVehicleCatalogue',r=>r.fulfill({json:{result:{stock:[],limited:false}}}));
 await page.route('**/publicImportDealers',r=>r.fulfill({json:{result:{dealers:[{slug:'import-motors',name:'Import Motors',operationMode:'sourcing'}],nextCursor:null}}}));
 let submitted:Record<string,unknown>|undefined;
 await page.route('**/enquireSupplierVehicle',r=>{submitted=r.request().postDataJSON().data;return r.fulfill({json:{result:{received:true,ref:'A1B2C3D4',dealer:{name:'Import Motors',slug:'import-motors',whatsapp:'+263771234567'}}}});});
 await page.route('**/publicSupplierVehicle',r=>r.fulfill({json:{result:{photos:vehicle.photos}}}));
 await page.goto('/');await expect(page.getByRole('heading',{name:vehicle.title,exact:true})).toBeVisible();
 await page.getByRole('link',{name:/View car & choose a dealer/}).click();await expect(page).toHaveURL(new RegExp('/imports/'+vehicle.id+'$'));
 await expect(page.getByText(`Supplier reference: ${vehicle.id}`)).toBeVisible();
 await expect.poll(()=>page.locator('.vehicle-main-photo').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`release-evidence/supplier-car-${width}.png`,fullPage:true});}
 await page.getByLabel('Choose your import dealer').selectOption('import-motors');await page.getByLabel('Your name',{exact:true}).fill('Test Buyer');await page.getByLabel('WhatsApp / phone').fill('+263771234567');await page.getByLabel('Total import budget').fill('10000');await page.getByRole('button',{name:'Request verification & quote'}).click();
 await expect(page.getByRole('status')).toContainText('Your request has reached Import Motors');expect(submitted?.supplierVehicleId).toBe(vehicle.id);expect(submitted?.slug).toBe('import-motors');expect(submitted?.budgetCents).toBe(1000000);
 await expect(page.getByText('Enquiry reference A1B2C3D4')).toBeVisible();
 await expect(page.getByRole('link',{name:'Continue on WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa\.me\/263771234567\?text=/);
 await expect(page.getByRole('link',{name:'Share this car'})).toHaveAttribute('href',/^https:\/\/wa\.me\/\?text=/);
 await page.getByRole('button',{name:'Download request (PDF)'}).click();
 const sheet=page.locator('.print-sheet');
 await expect(sheet.getByText('Import enquiry request — Radbit Auto')).toBeVisible();
 await expect(sheet.getByText(`Supplier reference: ${vehicle.id}`)).toBeVisible();
 await expect(sheet.getByText('Estimated landed cost in Zimbabwe: USD 7,800 - 9,600 (estimate as at 2026-10-09, not a quote)')).toBeVisible();
 await expect(sheet.getByText('Confirm availability of')).toBeVisible();
 await page.getByRole('button',{name:'Close document'}).click();
 await page.goto('/imports');
 await expect(page.getByRole('region',{name:'Your open import enquiry'})).toContainText('A1B2C3D4');
 await expect(page.getByRole('link',{name:'Return to this enquiry'})).toHaveAttribute('href',`/imports/${vehicle.id}`);
});
test('supplier failures retry; expired cars and no eligible dealers have useful states',async({page})=>{
 let failed=true;await page.route('**/publicSupplierCatalogue',r=>r.fulfill({json:failed?{error:{status:'UNAVAILABLE',message:'Supplier unavailable'}}:{result:{stock:[vehicle],limited:true}}}));
 await page.route('**/publicSupplierVehicle',r=>r.fulfill({json:{result:{photos:vehicle.photos}}}));
 await page.route('**/publicImportDealers',r=>r.fulfill({json:{result:{dealers:[],nextCursor:null}}}));
 await page.goto(`/imports/${vehicle.id}`);await expect(page.getByRole('button',{name:'Try again'})).toBeVisible();failed=false;await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByText('No participating import dealers are accepting enquiries yet.')).toBeVisible();
 await page.goto('/imports/EXPIRED');await expect(page.getByRole('link',{name:'Browse import vehicles'})).toBeVisible();
});

test('import detail shows supplier specifications and a labelled landed-cost estimate',async({page})=>{
 await page.route('**/publicSupplierCatalogue',r=>r.fulfill({json:{result:{stock:[{...vehicle,estimate}],limited:true}}}));
 await page.route('**/publicImportDealers',r=>r.fulfill({json:{result:{dealers:[],nextCursor:null}}}));
 await page.route('**/publicSupplierVehicle',r=>r.fulfill({json:{result:{photos:vehicle.photos,detail:{chassis:'M700A-0160915',colour:'Silver',drive:'2WD',seats:5,doors:5,weightKg:910,registration:'2020/3',engineCode:'1KR',body:'Hatchback'},estimate}}}));
 await page.goto('/imports');
 await expect(page.getByText('Est. landed in Zimbabwe: USD 7,800 - 9,600 (estimate)')).toBeVisible();
 await page.goto('/imports/'+vehicle.id);
 const panel=page.getByRole('region',{name:'Estimated landed cost in Zimbabwe'});
 await expect(panel).toContainText('USD 7,800 - 9,600');
 await expect(panel).toContainText('Estimate, not a quote.');
 await expect(panel.getByText('Customs duty (40% of CIF)')).toBeVisible();
 await expect(panel.getByText('Surtax (35%, vehicle 6 years old)')).toBeVisible();
 await expect(panel.getByText('Clearing, registration and dealer fee')).toBeVisible();
 await expect(panel.getByText('USD 300 - 750')).toBeVisible();
 await expect(panel.getByRole('note')).toHaveCount(0, 'a stated body type removes the assumed-rates warning');
 await expect(panel.getByText('How this is estimated')).toBeVisible();
 await panel.getByText('How this is estimated').click();
 await expect(panel.getByText(/Japan to Durban by RoRo: about USD 1,000-1,900/)).toBeVisible();
 const specs=page.locator('.supplier-detail-specs');
 await expect(specs.getByText('Hatchback')).toBeVisible();
 await expect(specs.getByText('M700A-0160915')).toBeVisible();
 await expect(specs.getByText('Silver')).toBeVisible();
 await expect(specs.getByText('2020/3')).toBeVisible();
 await expect(specs.getByText('2WD')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'release-evidence/supplier-landed-estimate.png',fullPage:true});
});
