import type { CSSProperties } from 'react';
import { Link, NavLink, Outlet } from 'react-router-dom';
import { useCompanyDoc } from '../lib/hooks';
import { useAuth } from '../lib/auth';
import { AccountIcon, CasesIcon, NewIcon, TeamIcon } from '../components/icons';
function toAccentVars(hex: string | undefined): CSSProperties {
  const h = (hex ?? '').trim().replace(/^#/, '');
  const full = h.length === 3 ? h.split('').map(c => c + c).join('') : h;
  const value = /^[0-9a-fA-F]{6}$/.test(full) ? parseInt(full,16) : parseInt('1f6a54',16);
  const r=(value>>16)&255,g=(value>>8)&255,b=value&255;
  return {'--accent-rgb':`${r} ${g} ${b}`,'--accent-ink-rgb':`${Math.round(r*.55)} ${Math.round(g*.55)} ${Math.round(b*.55)}`,'--accent-contrast-rgb':(r*299+g*587+b*114)/1000>165?'23 36 30':'255 255 255'} as CSSProperties;
}
const NAV=[{to:'/app',label:'My vehicles',icon:CasesIcon,end:true},{to:'/app/account',label:'Account',icon:AccountIcon,end:false}];
const STAFF_NAV=[{to:'/app',label:'Overview',icon:CasesIcon,end:true},{to:'/app/dealership',label:'Dealer',icon:NewIcon,end:false},{to:'/app/team',label:'Team',icon:TeamIcon,end:false},{to:'/app/operations',label:'Reports',icon:CasesIcon,end:false},{to:'/app/account',label:'Settings',icon:AccountIcon,end:false}];
export default function AppLayout(){
 const {user,claims}=useAuth();const isStaff=claims.appRole==='staff'||claims.appRole==='admin';const {data:company}=useCompanyDoc(claims.companyId);const nav=isStaff?STAFF_NAV:NAV;
 const subscription=company?.subscription;const expired=subscription?.version===1 && (!['trial','active'].includes(subscription.status??'') || !subscription.accessUntil || subscription.accessUntil.toMillis()<=Date.now());
 const days=subscription?.accessUntil?Math.max(0,Math.ceil((subscription.accessUntil.toMillis()-Date.now())/86400000)):null;
 const mark=(company?.casePrefix??company?.name??'RA').slice(0,2).toUpperCase(),prefix=company?.casePrefix??'',role=isStaff?claims.appRole??'staff':'customer';
 return <div className="app-shell mx-auto min-h-screen w-full pb-24 sm:max-w-2xl md:flex md:max-w-none md:pb-0" style={toAccentVars(company?.primaryColor)}>
 <header className="safe-top sticky top-0 z-40 border-b border-ink-800 bg-ink-950/95 backdrop-blur md:hidden"><div className="flex items-center gap-2.5 px-4 py-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-[11px] font-bold text-[rgb(var(--accent-contrast-rgb,255_255_255))] shadow-card" style={{backgroundColor:'rgb(var(--accent-rgb, 31 106 84))'}} aria-hidden>{company?.name?mark:<img src="/icons/radbit-auto-v2.svg" width="40" height="40" alt="" className="h-full w-full" />}</span><div className="min-w-0 flex-1"><p className="truncate font-display text-base font-bold tracking-tight text-slate-50">{company?.name??'Radbit Auto'}</p><p className="font-mono text-[10px] uppercase tracking-wider text-slate-500">{prefix?`${prefix} · `:''}{role}</p></div><span className="shrink-0 rounded-full border border-accent/30 bg-accent/10 px-2 py-0.5 text-[10px] font-semibold text-accent">{isStaff?'Agency':'Client'}</span></div></header>
 <aside className="hidden md:sticky md:top-0 md:flex md:h-screen md:w-64 md:shrink-0 md:flex-col md:border-r md:border-ink-800 md:bg-ink-900 md:px-4 md:py-6 xl:w-72"><div className="mb-2 flex items-center gap-3 px-2"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-sm font-bold text-[rgb(var(--accent-contrast-rgb,255_255_255))] shadow-card ring-1 ring-white/20" style={{backgroundColor:'rgb(var(--accent-rgb, 31 106 84))'}} aria-hidden>{company?.name?mark:<img src="/icons/radbit-auto-v2.svg" width="40" height="40" alt="" className="h-full w-full" />}</span><div className="min-w-0 flex-1"><p className="truncate font-display text-lg font-bold tracking-tight text-slate-50">{company?.name??'Radbit Auto'}</p><p className="mt-0.5 flex items-center gap-1.5 text-xs text-slate-500">{prefix?<span className="rounded-md bg-accent/15 px-1.5 py-px font-mono text-[10px] font-bold tracking-wider text-accent">{prefix}</span>:null}{isStaff?'imports pipeline':'customer portal'}</p></div></div>
 <nav className="mt-6 space-y-1" aria-label="Primary">{nav.map(n=><NavLink key={n.to} to={n.to} end={n.end} className={({isActive})=>`group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive?'text-slate-50':'text-slate-400 hover:text-slate-200'}`}>{({isActive})=><><span className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${isActive?'bg-accent/10 text-accent':'bg-ink-800/70 text-slate-500 group-hover:text-slate-300'}`} aria-hidden><n.icon className="h-[18px] w-[18px]"/></span>{n.label}</>}</NavLink>)}</nav><div className="mt-auto px-1 pt-4"><div className="rounded-xl border border-ink-800 bg-ink-950/60 p-3"><p className="truncate text-xs font-semibold text-slate-200">{user?.email??''}</p><p className="mt-0.5 font-mono text-[10px] uppercase tracking-wider text-slate-500">{role}{prefix?` · ${prefix}`:''}</p></div></div></aside>
 <main className="app-content min-w-0 flex-1 px-4 py-5 md:px-8 md:py-7 xl:px-10">{claims.appRole==='admin'?<div className="mb-4 flex justify-end"><Link to="/app/billing" className="text-sm text-accent">Plan & billing →</Link></div>:null}{isStaff && (expired || (days!==null && days<=7)) ? <div role="status" className="mb-4 rounded-xl border border-amber-700/50 p-3 text-sm text-amber-200">{expired?'Subscription is read-only. Existing records remain available.':`${days} days of subscription access remaining.`} {claims.appRole==='admin'?<Link to="/app/billing" className="underline">Open billing</Link>:'Ask your agency owner to arrange renewal.'}</div>:null}<Outlet/></main>
 <nav className="mobile-navigation safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-ink-800 bg-ink-950/95 backdrop-blur md:hidden" aria-label="Primary"><div className={`mx-auto grid max-w-md px-2 ${isStaff?'grid-cols-5':'grid-cols-2'}`}>{nav.map(n=><NavLink key={n.to} to={n.to} end={n.end} className={({isActive})=>`relative flex flex-col items-center gap-1 py-2.5 text-[10px] font-semibold transition ${isActive?'text-slate-50':'text-slate-500'}`}>{({isActive})=><><span className={`flex h-9 w-14 items-center justify-center rounded-xl transition ${isActive?'bg-accent/10 text-accent':'text-slate-500'}`} aria-hidden><n.icon className="h-5 w-5"/></span>{n.label}</>}</NavLink>)}</div></nav></div>;
}
