import { useEffect, useState } from 'react';
import { api, type SubscriptionOverview } from '../lib/api';
import { useAuth } from '../lib/auth';
import { Button, Card } from '../components/ui';
import { Link } from 'react-router-dom';

const collections = ['customers','staff','vehicles','import_cases','quotations','payments','dealer_leads','dealer_stock','dealer_costs','dealer_sales','dealer_sale_entries','dealer_sales_documents','dealer_acquisitions','import_deal_results','audit_log','subscription_events','agency_billing'];
export default function Billing() {
  const { claims } = useAuth();
  const [data,setData]=useState<SubscriptionOverview|null>(null);
  const [storage,setStorage]=useState<{date:string;storageBytes:number;storageObjects:number}|null>(null);
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{if(claims.appRole==='admin'){api.subscriptionOverview({}).then(setData).catch(e=>setMessage(e.message));api.agencyUsageHistory({}).then(usage=>setStorage(usage.rows[0]??null)).catch(()=>{});}},[claims.appRole]);
  if(claims.appRole!=='admin')return <Card><p>Billing and business exports are available to the agency owner.</p></Card>;
  async function request(planId:'solo'|'dealer') {setBusy(true);setMessage('');try {await api.requestSubscriptionPlan({planId});setData(await api.subscriptionOverview({}));setMessage('Request recorded. Contact support to arrange your USD invoice. Access changes after payment verification.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function exportRecords() {
    setBusy(true);setMessage('Preparing your private business export…');
    try {
      const result:Record<string,unknown[]>={};
      async function read(collection:string,parentId?:string,childCollection?:string){const rows:Record<string,unknown>[]=[];let cursor:string|null=null;do{const page=await api.exportAgencyRecords({collection,...(cursor?{cursor}:{}),...(parentId?{parentId,childCollection}:{})});rows.push(...page.rows);cursor=page.nextCursor;}while(cursor);return rows;}
      for(const collection of collections)result[collection]=await read(collection);
      for(const collection of ['import_cases','dealer_acquisitions'])for(const parent of result[collection] as {id:string}[])for(const child of collection==='import_cases'?['supplier','stage_updates','tracking','documents']:['events'])result[`${collection}/${parent.id}/${child}`]=await read(collection,parent.id,child);
      const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),companyId:claims.companyId,formatVersion:1,records:result},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`agency-records-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Business records exported. Keep this file private: it contains customer information and costs. Photos and document files are not included.');
    }catch(e){setMessage(`Export failed; no partial file downloaded. ${(e as Error).message}`);}finally{setBusy(false);}
  }
  return <div className="mx-auto max-w-3xl space-y-5"><div><Link to="/app/account" className="text-sm text-accent">← Settings</Link><h1 className="mt-3 font-display text-3xl font-bold">Plan & billing</h1><p className="mt-2 text-sm text-slate-400">USD monthly subscriptions. Customer portal accounts are free.</p></div>
    {data?<Card><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">{data.managed?`${data.name} · $${data.monthlyCents/100}/month`:'Existing pilot access'}</h2><span className="rounded border border-accent/30 px-3 py-1 text-sm">{data.status.replaceAll('_',' ')}</span></div><p className="mt-3">{data.accessUntil?`Access through ${new Date(data.accessUntil).toLocaleDateString()}. ${data.daysRemaining} days remaining.`:'Existing pilot access. Contact support to agree your plan and start date.'}</p>{!data.writable?<p className="mt-2 text-amber-300">Your workspace is read-only. Existing records and customer portals remain available; renew to resume business updates.</p>:null}<div className="mt-4 grid grid-cols-2 gap-4"><p><strong>{data.usedSeats} / {data.seats}</strong><br/><span className="text-sm text-slate-400">Active team members, owner included</span></p><p><strong>{data.usedActiveVehicles} / {data.activeVehicles}</strong><br/><span className="text-sm text-slate-400">Active vehicles and enquiries</span></p></div><p className="mt-3 text-xs text-slate-400">Available/reserved stock, unfinished customer imports and dealer acquisitions count once per vehicle. Enquiries without a selected vehicle count individually. Completed history is retained.</p>{data.invoiceReference?<p className="mt-3 text-sm">Invoice: {data.invoiceReference}</p>:null}{data.requestedPlan?<p className="mt-2 text-sm">Requested plan: {data.requestedPlan}</p>:null}</Card>:<p>{message?'Subscription details could not be loaded. Refresh to try again.':'Loading your subscription…'}</p>}
    <Card><h2 className="section-title">Choose your capacity</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-2 pr-2">Plan</th><th className="px-2">USD/month</th><th className="px-2">Team</th><th className="pl-2">Active vehicles</th></tr></thead><tbody>{(['solo','dealer'] as const).map(id=><tr key={id} className="border-t border-ink-800"><td className="py-3 pr-2 capitalize">{id}</td><td className="px-2">${id==='solo'?15:29}</td><td className="px-2">{id==='solo'?2:5}</td><td className="pl-2">{id==='solo'?15:50}</td></tr>)}</tbody></table></div><div className="mt-3 grid grid-cols-2 gap-3">{(['solo','dealer'] as const).map(id=><Button key={id} disabled={busy} onClick={()=>request(id)}>Request {id}</Button>)}</div><p className="mt-3 text-sm text-slate-400">Both plans include the core stock, import, sales, documents and customer portal workflows. Plan requests do not charge you or grant access automatically.</p><a className="mt-3 inline-block text-accent" href="mailto:brandontinoz@gmail.com?subject=Agency%20subscription">Arrange payment with support</a></Card>
    {storage?<Card><h2 className="section-title">Storage usage</h2><p className="mt-2 text-sm">{(storage.storageBytes/1024/1024).toFixed(1)} MB in {storage.storageObjects} files, measured {storage.date}.</p></Card>:null}<Card><h2 className="section-title">Your business records</h2><p className="mb-3 mt-2 text-sm text-slate-400">Download a JSON export of customers, stock, cases, quotations, payment records, sales, costs and history. File attachments are excluded. Records can change while the export runs; this is a data export, not a point-in-time backup.</p><Button disabled={busy} onClick={exportRecords}>Export business records</Button></Card>{message?<p role="status" className="break-words text-sm">{message}</p>:null}
  </div>;
}
