import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { dealerCall } from '../lib/dealer';
import { Button,Card,Input,Select } from '../components/ui';
import { parseCsv,readWorkbook,downloadCsv,importFields } from '../lib/bulkImport';
import { VEHICLE_CATEGORIES } from '../lib/types';
type Result={rowNumber:number;status:string;message:string;summary?:string;recordId?:string};
export default function BulkImport(){
 const {claims}=useAuth();const [kind,setKind]=useState<'customers'|'stock'>('customers'),[sheets,setSheets]=useState<{name:string;rows:string[][]}[]>([]),[sheet,setSheet]=useState(0),[header,setHeader]=useState(1),[start,setStart]=useState(2),[end,setEnd]=useState(101),[mapping,setMapping]=useState<Record<string,string>>({}),[category,setCategory]=useState(''),[delimiter,setDelimiter]=useState(','),[csv,setCsv]=useState(''),[results,setResults]=useState<Result[]>([]),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filename,setFilename]=useState('');
 const table=sheets[sheet]?.rows??[];const headers=table[header-1]??[];const fields=importFields[kind];
 function reset(){setResults([]);setPreview(false);setError('');}
 function suggest(row:string[]){const map:Record<string,string>={};for(const [key,,aliases] of importFields[kind]){const found=row.findIndex(h=>aliases.split(',').includes(h.toLowerCase().replace(/[^a-z0-9]/g,'')));if(found>=0)map[key]=String(found);}setMapping(map);}
 async function load(file:File){reset();setBusy(true);try{if(file.size>2*1024*1024)throw new Error('Use a file smaller than 2 MB');let data;if(/\.csv$/i.test(file.name)){const text=await file.text();setCsv(text);data=[{name:'CSV',rows:parseCsv(text,delimiter)}];}else{setCsv('');data=await readWorkbook(file);}setSheets(data);setSheet(0);setHeader(1);setStart(2);setEnd(Math.min(data[0]?.rows.length??1,101));suggest(data[0]?.rows[0]??[]);setFilename(file.name);}catch(e){setError((e as Error).message);setSheets([]);}finally{setBusy(false);}}
 function payload(){if(!headers.length)throw new Error('Choose a header row');if(!Number.isInteger(start)||!Number.isInteger(end)||start<=header||end<start||end>table.length||end-start+1>100)throw new Error('Choose 1–100 data rows after the header, within the worksheet');const columns=Object.values(mapping).filter(v=>v!=='');if(new Set(columns).size!==columns.length)throw new Error('Map each column to only one field');return table.slice(start-1,end).flatMap((row,index)=>{if(row.every(c=>!c.trim()))return [];const record:Record<string,unknown>={rowNumber:start+index};for(const [key] of fields)record[key]=mapping[key]!==undefined&&mapping[key]!==''?row[Number(mapping[key])]??'':'';if(kind==='stock'&&!record.category)record.category=category;if(Object.values(record).includes('#UNSUPPORTED_CELL'))throw new Error(`Row ${start+index} contains a formula or error. Paste values into that cell before importing.`);return [record];});}
 async function run(mode:'preview'|'commit'){setBusy(true);setError('');try{const rows=payload();const data=await dealerCall<{results:Result[]}>('bulkImportRecords',{kind,mode,rows},{timeout:330000});setResults(data.results);setPreview(mode==='preview');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(claims.appRole!=='admin')return <p>Only the agency owner can import records.</p>;
 return <div className="space-y-5 pb-8"><header><p className="interface-eyebrow">Bring your existing records</p><h1 className="font-display text-3xl">Import customers or stock</h1><p className="my-3">Upload CSV or Excel (.xlsx), map your columns and review before importing. Up to 100 data rows per batch, 2 MB per file. Files are read on your device; only mapped rows are submitted.</p><Link className="underline" to="/app/team">Back to Team</Link></header>{error&&<p role="alert">{error}</p>}<Card><h2 className="section-title">1. Choose your table</h2><label>Record type<Select aria-label="Record type" value={kind} disabled={busy} onChange={e=>{setKind(e.target.value as typeof kind);setMapping({});reset();}}><option value="customers">Customers</option><option value="stock">Available stock</option></Select></label><p className="my-3 text-sm">{kind==='customers'?'Creates customer records without login access. Invite customers separately after import.':'For vehicles already available to sell. Stock stays unpublished. Imported prices do not create sales or confirmed payments. Blank costs remain unknown.'}</p><Button variant="ghost" onClick={()=>downloadCsv(`${kind}-template.csv`,kind==='customers'?[['Customer Name','Phone']]:[['VIN','Make','Model','Year','Category','Asking Price','Location','Ownership','Acquisition Cost','Direct Costs','Costs Complete']])}>Download CSV template</Button><label className="mt-4 block">CSV delimiter<Select aria-label="CSV delimiter" value={delimiter} disabled={busy} onChange={e=>{setDelimiter(e.target.value);reset();if(csv){try{const rows=parseCsv(csv,e.target.value);setSheets([{name:'CSV',rows}]);setEnd(Math.min(rows.length,101));setMapping({});}catch(e){setError((e as Error).message);}}}}><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option></Select></label><label className="mt-4 block">Upload file<Input aria-label="Upload file" type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void load(file);}}/></label>{filename&&<p className="mt-2 text-sm break-words">{filename}</p>}</Card>
 {table.length>0&&<><Card><h2 className="section-title">2. Select rows and map columns</h2><div className="grid gap-3 sm:grid-cols-2"><label>Worksheet<Select aria-label="Worksheet" disabled={busy} value={sheet} onChange={e=>{const n=Number(e.target.value);setSheet(n);setHeader(1);setStart(2);setEnd(Math.min(sheets[n].rows.length,101));setMapping({});reset();}}>{sheets.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</Select></label><label>Header row<Input aria-label="Header row" type="number" min="1" max={table.length} value={header} disabled={busy} onChange={e=>{setHeader(Number(e.target.value));setMapping({});reset();}}/></label><label>First data row<Input aria-label="First data row" type="number" value={start} disabled={busy} onChange={e=>{setStart(Number(e.target.value));reset();}}/></label><label>Last data row<Input aria-label="Last data row" type="number" value={end} disabled={busy} onChange={e=>{setEnd(Number(e.target.value));reset();}}/></label></div><Button className="my-4" variant="ghost" disabled={busy} onClick={()=>{suggest(headers);reset();}}>Suggest column matches</Button><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key}>{label}<Select aria-label={label} disabled={busy} value={mapping[key]??''} onChange={e=>{setMapping({...mapping,[key]:e.target.value});reset();}}><option value="">Not mapped</option>{headers.map((h,i)=><option key={i} value={i}>{i+1}: {h||'(blank heading)'}</option>)}</Select>{mapping[key]!==undefined&&mapping[key]!==''&&<p className="mt-1 break-words text-sm">Sample: {table[start-1]?.[Number(mapping[key])]?.slice(0,100)||'(blank)'}</p>}</label>)}</div>{kind==='stock'&&<label className="mt-4 block">Category for rows without a category<Select aria-label="Default category" value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);reset();}}><option value="">Choose if needed</option>{VEHICLE_CATEGORIES.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</Select></label>}<p className="my-4 text-sm">{kind==='customers'?'Customers need a name and phone. Use Zimbabwe local numbers beginning 0 or +country-code numbers, with phone columns formatted as text. No login account is created.':'Stock needs VIN/chassis, make, model, year, category, asking price and location. Ownership defaults to owned. For complete costs, provide acquisition/settlement cost and direct costs, including explicit zero where appropriate. Category cells use the template field values.'}</p><Button disabled={busy} loading={busy} onClick={()=>void run('preview')}>Validate and preview</Button></Card></>}
 {results.length>0&&<Card><h2 className="section-title">3. Review {preview?'before import':'import results'}</h2><p className="my-3" role="status">{results.filter(r=>r.status==='ready').length} ready · {results.filter(r=>r.status==='imported').length} imported · {results.filter(r=>r.status==='duplicate').length} duplicates skipped · {results.filter(r=>r.status==='error').length} errors</p><ul className="divide-y">{results.map((r,i)=><li key={i} className="py-3 break-words">Row {r.rowNumber}: <strong>{r.status}</strong>{r.summary&&<p className="text-sm">{r.summary}</p>}{r.message&&<p className="text-sm">{r.message}</p>}</li>)}</ul><Button variant="ghost" onClick={()=>downloadCsv('import-results.csv',[['Row','Status','Message'],...results.map(r=>[String(r.rowNumber),r.status,r.message])])}>Download results CSV</Button>{preview&&<><p className="my-4">Only valid, new rows will be imported. Invalid and duplicate rows are skipped. Existing records are never overwritten. Review your mappings and sample values before proceeding.</p><Button loading={busy} disabled={busy||!results.some(r=>r.status==='ready')} onClick={()=>void run('commit')}>Import valid rows</Button></>}</Card>}</div>;
}




