import { useEffect,useState,type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { useVehicles } from '../lib/hooks';
import { dealerCall,dealerCents,dealerMoney as money } from '../lib/dealer';
import { Button,Card,Input,Select,TextArea } from '../components/ui';
import { PageHeader } from '../components/status';
type Acquisition={id:string;title:string;stage:string;supplier:string;supplierReference:string;supplierUrl:string;purchaseCents:number;directCostsCents:number};
type Event={id:string;action:string;category?:string;stage?:string;amountCents:number;evidence:string};
const stages=['selected','purchased','shipped','arrived','cleared','prepared','stocked'];
export default function DealerAcquisitions(){
  const {claims}=useAuth();const owner=claims.appRole==='admin';const {data:vehicles}=useVehicles(owner?claims.companyId:undefined);const [acquisitions,setAcquisitions]=useState<Acquisition[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [events,setEvents]=useState<Record<string,Event[]>>({});
  async function load(){const d=await dealerCall<{dealer_acquisitions:Acquisition[]}>('dealershipWorkspace',{});setAcquisitions(d.dealer_acquisitions);}
  useEffect(()=>{if(owner)void load().catch(e=>setError(e.message));},[owner,claims.companyId]);
  async function submit(e:FormEvent<HTMLFormElement>,name:string,transform:(f:FormData)=>object){e.preventDefault();const form=e.currentTarget;form.dataset.requestId??=crypto.randomUUID();setBusy(true);setError('');try{await dealerCall(name,{...transform(new FormData(form)),requestId:form.dataset.requestId});await load();form.reset();delete form.dataset.requestId;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!owner)return <p>Dealer acquisitions and acquisition costs are available to the owner.</p>;
  return <div className="space-y-5 pb-8"><PageHeader title="Dealer acquisitions" subtitle="Buy, land and prepare your own vehicles before offering them for sale"/><Link className="btn-ghost" to="/app/dealership">Back to dealership</Link>{error&&<p role="alert">{error}</p>}
    <Card><h2 className="mb-4 text-xl font-semibold">Start a stock acquisition</h2><Link className="btn-ghost mb-4" to="/app/new/vehicle">Register acquisition vehicle</Link><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>submit(e,'createDealerAcquisition',f=>Object.fromEntries(f))}><label>Vehicle<Select required name="vehicleId" aria-label="Acquisition vehicle"><option value="">Choose unallocated vehicle</option>{vehicles.filter(v=>!v.customerIds?.length&&!acquisitions.some(a=>a.id===v.id)).map(v=><option key={v.id} value={v.id}>{v.year} {v.make} {v.model} · {v.vinChassisUpper}</option>)}</Select></label><label>Supplier<Input required name="supplier" aria-label="Acquisition supplier" placeholder="BE FORWARD or another supplier"/></label><label>Supplier stock / invoice reference<Input required name="supplierReference" aria-label="Supplier acquisition reference"/></label><label>Supplier link<Input name="supplierUrl" type="url" aria-label="Supplier acquisition link" placeholder="https://"/></label><Button loading={busy}>Start acquisition</Button></form><p className="mt-3 text-sm">Purchase and supplier payments happen outside this portal. Record confirmed costs and references here.</p></Card>
    {acquisitions.map(a=><Card key={a.id}><h2 className="text-xl font-semibold">{a.title}</h2><p>{a.supplier} · {a.supplierReference}</p>{a.supplierUrl&&<a className="underline" href={a.supplierUrl} target="_blank" rel="noreferrer">Open supplier reference</a>}<p className="my-3">Stage: <strong>{a.stage}</strong></p><ol className="flex flex-wrap gap-2 text-xs">{stages.map(s=><li key={s} className="rounded border px-2 py-1" aria-current={s===a.stage?'step':undefined}>{s}</li>)}</ol><p className="my-4">Purchase {money(a.purchaseCents)} · Landing/preparation {money(a.directCostsCents)} · Recorded cost {money(a.purchaseCents+a.directCostsCents)}</p>
      {a.stage!=='stocked'&&<>
        <form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>submit(e,'updateDealerAcquisition',f=>({...Object.fromEntries(f),acquisitionId:a.id,action:'cost',amountCents:dealerCents(f.get('amount'))}))}><label>Actual cost category<Select name="category" aria-label={`Cost category for ${a.title}`}>{['purchase','freight','customs','preparation','other'].map(c=><option key={c}>{c}</option>)}</Select></label><label>Actual amount (USD)<Input required type="number" min="0.01" step="0.01" name="amount" aria-label={`Cost amount for ${a.title}`}/></label><label className="sm:col-span-2">Paid invoice / expense reference<Input required name="evidence" aria-label={`Cost evidence for ${a.title}`}/></label><Button loading={busy}>Record actual cost</Button></form>
        {a.stage!=='prepared'?<form className="mt-5 space-y-3 border-t pt-4" onSubmit={e=>submit(e,'updateDealerAcquisition',f=>({...Object.fromEntries(f),acquisitionId:a.id,action:'advance'}))}><label>Stage evidence<TextArea required name="evidence" aria-label={`Stage evidence for ${a.title}`}/></label><Button loading={busy}>Advance to {stages[stages.indexOf(a.stage)+1]}</Button></form>:<form className="mt-5 grid gap-3 border-t pt-4 sm:grid-cols-2" onSubmit={e=>submit(e,'updateDealerAcquisition',f=>({...Object.fromEntries(f),acquisitionId:a.id,action:'transfer',askingPriceCents:dealerCents(f.get('asking')),costsComplete:f.get('complete')==='on'}))}><label>Stock location<Input required name="location" aria-label={`Stock location for ${a.title}`}/></label><label>Asking price (USD)<Input required type="number" min="0.01" step="0.01" name="asking" aria-label={`Stock asking price for ${a.title}`}/></label><label>Preparation / readiness evidence<Input required name="evidence" aria-label={`Transfer evidence for ${a.title}`}/></label><label className="flex items-center gap-2"><input required type="checkbox" name="complete"/>All actual acquisition costs are recorded</label><Button loading={busy}>Transfer into available stock</Button></form>}
      </>}
      <Button className="mt-4" variant="ghost" onClick={async()=>{try{const d=await dealerCall<{events:Event[]}>('dealerAcquisitionDetails',{acquisitionId:a.id});setEvents({...events,[a.id]:d.events});}catch(e){setError((e as Error).message);}}}>View acquisition history</Button>{events[a.id]?.map(e=><p key={e.id} className="mt-2 break-words text-sm">{e.action} {e.category??e.stage??''} · {money(e.amountCents)} · {e.evidence}</p>)}
    </Card>)}
  </div>;
}
