import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { reload, signOut } from 'firebase/auth';
import { auth } from '../lib/firebase';
import { useAuth } from '../lib/auth';
import { api } from '../lib/api';
import { dealerCall } from '../lib/dealer';
import { Button, Card } from '../components/ui';
import EmailVerification from '../components/EmailVerification';
type Info={agencyName:string;role:string;status:string;expiresAt:number};
export default function Invitation(){
 const {token=''}=useParams();const {user,waitForClaims}=useAuth();const navigate=useNavigate();const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[info,setInfo]=useState<Info>(),[error,setError]=useState('');const next=encodeURIComponent(`/invite/${token}`);
 useEffect(()=>{let active=true;setInfo(undefined);setError('');dealerCall<Info>('invitationInfo',{token}).then(d=>{if(active)setInfo(d);}).catch(()=>{if(active)setError('This invitation is unavailable. Check the full link or ask the agency for a new invitation.');});return()=>{active=false;};},[token]);
 async function accept(){if(!user)return;setBusy(true);setMessage('');try{await reload(user);await user.getIdToken(true);if(!user.emailVerified){setMessage('Verify your email before accepting this invitation.');return;}await api.acceptInvitation({token});const claims=await waitForClaims();if(claims?.companyId)navigate('/app',{replace:true});else setMessage('Your invitation was accepted, but your session is not updated yet. Sign out and sign back in to open your workspace.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-xl px-5 py-12"><Card><p className="interface-eyebrow">Private invitation</p><h1 className="font-display text-3xl">{info?`Join ${info.agencyName}`:'Your workspace invitation'}</h1>{error?<p role="alert" className="my-4">{error}</p>:!info?<p role="status" className="my-4">Checking invitation…</p>:<><p className="my-4">{info.role==='customer'?'Customer access: view your linked vehicles, payments and documents.':'Staff access: work with the agency’s operational records.'}</p><p className="mb-4 text-sm">Use the email your agency invited. Expires {new Date(info.expiresAt).toLocaleDateString()}. Your existing vehicle history stays linked.</p>{info.status!=='pending'&&info.status!=='accepted'?<><p role="alert">This invitation is {info.status}. Ask the agency for a new link.</p><a className="btn-ghost mt-3 inline-flex" href={`mailto:brandontinoz@gmail.com?subject=${encodeURIComponent(`New invitation link needed${info?` - ${info.agencyName}`:''}`)}&body=${encodeURIComponent(`Agency: ${info?.agencyName ?? 'unknown'}\nInvitation token: ${token}\nStatus: ${info?.status ?? 'unknown'}\n\nPlease ask my agency to send me a new invitation link.`)}`}>Request a new link from support</a></>:info.status==='accepted'?<><p role="status">This invitation has already been accepted.</p><Link className="btn-primary mt-4" to="/login">Sign in to your workspace</Link></>:!user?<div className="flex flex-col gap-3"><Link className="btn-primary" to={`/login?mode=signup&next=${next}`}>Create my account</Link><Link className="btn-ghost" to={`/login?next=${next}`}>Sign in to accept</Link></div>:<><p className="mb-3 break-all">Signed in as {user.email}</p><>{!user.emailVerified&&<EmailVerification returnPath={`/invite/${token}`} />}<Button onClick={accept} loading={busy} disabled={!user.emailVerified}>Verify email and accept invitation</Button></><Button variant="ghost" onClick={()=>signOut(auth)} disabled={busy}>Use a different account</Button></>}</>}{message&&<p role="status" className="mt-4 text-sm">{message}</p>}<Link className="mt-5 inline-block underline text-sm" to="/help">Need help?</Link></Card></main>;
}
