import SupplierInventory from '../components/SupplierInventory';
import PublicStockBrowser, { type PublicStock } from '../components/PublicStockBrowser';
import Brand from '../components/Brand';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../lib/firebase';
import Seo from '../components/Seo';
import '../marketing.css';

export default function Landing(){
 const [inventory,setInventory]=useState<'import'|'local'>('import');
 const [stock,setStock]=useState<PublicStock[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0),[limited,setLimited]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);setError(false);httpsCallable(functions,'publicVehicleCatalogue')({}).then(r=>{if(active){const d=r.data as {stock:PublicStock[];limited:boolean};setStock(d.stock);setLimited(d.limited);}}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[retry]);
 const dealers=[...new Map(stock.map(s=>[s.slug,{slug:s.slug,name:s.dealerName}])).values()];
 return <div className="marketing-page automotive-landing"><Seo title="Radbit Auto — Cars in Zimbabwe. Imports on your behalf." description="Find cars offered by Zimbabwe dealers or enquire about an import. Dealerships can manage stock, customer imports, sales and buyer updates in one workspace." path="/" /><header className="marketing-header"><Link to="/" className="product-wordmark"><Brand tagline /></Link><nav aria-label="Public navigation"><a href="#cars">Find a car</a><a href="#dealers">For dealers</a><a href="#pricing" className="pricing-nav">Plans</a><Link to="/login" className="public-signin">Sign in</Link></nav></header><main>
 <section className="marketing-hero buyer-hero"><div><p className="interface-eyebrow">Cars in Zimbabwe. Imports on your behalf.</p><h1>Find your next car.<br/><span>Stay informed at every step.</span></h1><p className="marketing-lead">Find a car from participating dealers, or ask for an import. Talk on WhatsApp. Keep your purchase, payments and progress together.</p><div className="marketing-actions"><a href="#cars" className="btn-primary">Browse available cars</a><Link to="/imports" className="btn-ghost">Browse import cars</Link></div><p className="interface-note">Already buying? <Link to="/login" className="underline">Sign in to view your vehicles.</Link></p></div><figure className="automotive-hero-art"><div className="art-topline"><span>A new chapter starts here.</span><span aria-hidden="true">01 / ZW</span></div><img src="/images/vehicle-journey-1000.webp" srcSet="/images/vehicle-journey-600.webp 600w, /images/vehicle-journey-1000.webp 1000w, /images/vehicle-journey-1440.webp 1440w" sizes="(max-width: 767px) calc(100vw - 44px), (max-width: 1344px) 46vw, 600px" width="1440" height="1080" alt="Silver crossover beside a road in a sunlit highveld landscape" fetchPriority="high"/><figcaption><span>From the first enquiry<br/><strong>to your next adventure.</strong></span><a href="#cars" aria-label="Explore available cars">↗</a></figcaption></figure></section>
 <section className="journey-strip" aria-label="Your buying journey"><p className="interface-eyebrow">A clearer way<br/>to your next car</p><ol>{[['01','Explore or source','Browse dealer stock or share your brief.'],['02','Talk to your dealer','Agree condition, price and terms directly.'],['03','Follow your purchase','Keep recorded payments and progress together.']].map(([n,t,d])=><li key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></li>)}</ol></section>
 <section id="cars" className="marketing-section"><div className="catalogue-heading"><div><p className="interface-eyebrow">Browse inventory</p><h2>Start with a car you can see.</h2></div><p>Imported cars ship from Japan with BE FORWARD. Local cars are with a dealer in Zimbabwe.<br/>Prices are in USD.</p></div><div className="stock-card-actions mb-5" aria-label="Inventory type"><button className={inventory==='import'?'btn-primary':'btn-ghost'} aria-pressed={inventory==='import'} onClick={()=>setInventory('import')}>Cars to import</button><button className={inventory==='local'?'btn-primary':'btn-ghost'} aria-pressed={inventory==='local'} onClick={()=>setInventory('local')}>Cars available locally</button></div>{inventory==='import'?<SupplierInventory/>:loading?<p role="status" className="py-8">Loading published vehicles…</p>:error?<div className="catalogue-empty" role="alert"><p>We couldn’t load the cars right now.</p><button className="btn-ghost mt-3" onClick={()=>setRetry(n=>n+1)}>Try again</button></div>:<PublicStockBrowser stock={stock} limited={limited}/>}</section><section id="sourcing" className="marketing-section marketing-workflow sourcing-story"><div><p className="interface-eyebrow">A specific car in mind?</p><h2>Tell a dealer your brief.<br/>Follow your import.</h2></div><div><p>Share the model, budget and preferences with your dealer. They can prepare an itemised USD quotation and record supplier references, import documents and confirmed payments.</p><p>Once your dealer links your account, check the import stage, next step and balance from your phone.</p>{dealers.length?<div className="dealer-links">{dealers.map(d=><Link className="btn-ghost" key={d.slug} to={`/showroom/${d.slug}`}>Enquire with {d.name}</Link>)}</div>:<p className="interface-note">Ask your dealer for their showroom link to send an enquiry. Customer accounts are connected by the dealer; creating an agency workspace is for businesses.</p>}</div></section>
 <section id="dealers" className="marketing-section dealer-pitch"><span className="dealer-section-number" aria-hidden="true">FOR YOUR BUSINESS /</span><div><p className="interface-eyebrow">For dealerships, sourcing &amp; clearing agencies</p><h2>Your stock. Your customers.<br/>One connected workspace.</h2><p className="marketing-lead">Turn your showroom and WhatsApp enquiries into organised sales. Manage your own inventory alongside vehicles imported on behalf of customers.</p><div className="marketing-actions"><Link to="/login?intent=agency&mode=signup" className="btn-primary">Create your agency workspace</Link><a href="mailto:brandontinoz@gmail.com?subject=Dealership%20workspace%20enquiry" className="btn-ghost">Discuss your workspace</a></div><p className="interface-note">Start with a 14-day Dealer trial. Then choose Solo at $15/month or Dealer at $29/month, in USD. Customer accounts are free.</p></div><dl className="dealer-capabilities">{[['Sell from stock','Publish photos and prices, capture enquiries, reserve vehicles and record payment and handover.'],['Import for customers or your stock','Track customer imports separately from dealer acquisitions and landed costs.'],['Give buyers clarity','Share private purchase access, printable agreements, receipts and balance statements.'],['Understand your deals','Keep supplier payments, agency fees and stock costs distinct in owner reports.']].map(([t,d])=><div key={t}><dt>{t}</dt><dd>{d}</dd></div>)}</dl></section>
 <section id="pricing" className="marketing-section pricing-story"><div className="pricing-intro"><p className="interface-eyebrow">Simple plans. USD pricing.</p><h2>A workspace that<br/>grows with your business.</h2><p>All the essentials on either plan: stock, customer imports, sales, documents, customer portals and CSV/Excel import.</p><p className="pricing-trial-note">Your first 14 days are on us.<br/><strong>Start with the Dealer trial. No automatic debit.</strong></p></div><div className="pricing-plans">{[{name:'Solo',price:15,seats:2,vehicles:15,detail:'For an independent agent or small team.'},{name:'Dealer',price:29,seats:5,vehicles:50,detail:'For a growing dealership and its team.'}].map(plan=><article key={plan.name} className={`marketing-plan ${plan.name==='Dealer'?'dealer-plan':''}`}><p className="plan-caption">{plan.name==='Dealer'?'Your 14-day trial plan':'A focused start'}</p><h3>{plan.name}</h3><p className="plan-price"><strong>${plan.price}</strong><span>USD / month</span></p><p className="plan-description">{plan.detail}</p><ul><li><strong>{plan.seats}</strong> business team members</li><li><strong>{plan.vehicles}</strong> active vehicles / enquiries</li><li>Free customer portal accounts</li><li>All core workflows included</li></ul><Link to="/login?intent=agency&mode=signup" className={plan.name==='Dealer'?'btn-primary':'btn-ghost'}>{plan.name==='Dealer'?'Start your 14-day Dealer trial':'Start with a free Dealer trial'}</Link></article>)}</div><p className="pricing-fine-print">The owner counts as a team member. Active vehicles include available/reserved stock, unfinished customer imports and dealer acquisitions; enquiries without a vehicle count individually. Completed history is retained. Payment is arranged manually with support.</p></section>
 <section className="marketing-section marketing-workflow connected-story"><div><p className="interface-eyebrow">Fits how you already work</p><h2>WhatsApp for conversation.<br/>The portal for the record.</h2></div><div><p>Continue purchasing through BE FORWARD or your chosen supplier. Keep public listing and invoice references with the relevant vehicle.</p><p>Send buyers a WhatsApp link to their showroom, purchase or import record.</p><p className="interface-note">Supplier purchases, messages and payment transfers are handled outside the portal. No supplier partnership or automatic payment is claimed.</p></div></section></main><footer className="marketing-footer"><span><Brand /><br/><a href="https://radbitstudios.co.zw" target="_blank" rel="noopener noreferrer">By Radbit Studios</a> · Zimbabwe · USD</span><div><Link to="/help">Support &amp; privacy</Link><Link to="/login">Customer &amp; dealer sign in</Link></div></footer></div>;
}
