import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { dealerCall, dealerMoney as money } from '../lib/dealer';
import { Button, Card, Input } from '../components/ui';
import { PageHeader } from '../components/status';

type Entry={id:string;action:string;amountCents:number;evidence:string;date:string};
type SalesDocument={vin?:string;customerPhone?:string;agencyWhatsapp?:string;handoverEvidence?:string;id:string;kind:string;number:string;issuedAt:string;agency:string;customer:string;title:string;saleReference:string;terms:string;agreedPriceCents:number;paidCents:number;balanceCents:number;status:string;entry:Entry|null};
type Detail={sale:{vin?:string;photos?:string[];id:string;title:string;customerName:string;customerId:string;status:string;agreedPriceCents:number;paidCents:number;terms:string;expiresAt:string;documentNumber:string};agency:{name:string;whatsapp:string};entries:Entry[];documents:SalesDocument[]};
export function RetailPurchaseCards() {
  const {claims}=useAuth();const [sales,setSales]=useState<{id:string;title:string;status:string;agreedPriceCents:number;paidCents:number}[]>([]);const [error,setError]=useState('');
  useEffect(()=>{let active=true;dealerCall<{sales:typeof sales}>('customerRetailPurchases',{}).then(d=>{if(active)setSales(d.sales);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[claims.customerId]);
  return <section className="mb-6 space-y-3"><h2 className="font-display text-2xl">My purchases</h2>{error&&<p role="alert">{error}</p>}{sales.length===0&&!error&&<p className="text-sm">Your reserved or purchased stock vehicles will appear here.</p>}<div className="grid gap-3 xl:grid-cols-2">{sales.map(s=><Card key={s.id}><h3 className="text-lg font-semibold">{s.title}</h3><p>{s.status} · Confirmed {money(s.paidCents)}</p><p>Balance {money(s.agreedPriceCents-s.paidCents)}</p><Link className="btn-primary mt-3" to={`/app/purchases/${s.id}`}>View purchase</Link></Card>)}</div></section>;
}
export default function RetailPurchase() {
  const {saleId}=useParams();const {claims}=useAuth();const staff=['admin','staff'].includes(claims.appRole??'');
  const [data,setData]=useState<Detail>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [sheet,setSheet]=useState<SalesDocument>();const [invite,setInvite]=useState('');
  async function load(){setData(await dealerCall<Detail>('dealerSaleDetails',{saleId}));}
  useEffect(()=>{let active=true;const refresh=()=>{if(document.visibilityState==='visible')void dealerCall<Detail>('dealerSaleDetails',{saleId}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});};refresh();const timer=setInterval(refresh,45000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[saleId,claims.companyId]);
  async function issue(kind:string,entryId?:string){setBusy(true);setError('');try{const result=await dealerCall<{documentId:string}>('issueDealerSaleDocument',{saleId,kind,entryId,requestId:crypto.randomUUID()});const latest=await dealerCall<Detail>('dealerSaleDetails',{saleId});setData(latest);setSheet(latest.documents.find(d=>d.id===result.documentId));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="space-y-4 pb-8"><PageHeader title={data?.sale.title??'Purchase'} subtitle="Agreed terms, confirmed payments and vehicle collection" /><Button variant="ghost" onClick={()=>void load().catch(e=>setError(e.message))}>Refresh purchase</Button>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading purchase…</p>}{data&&<>
    <Card><h2 className="text-xl font-semibold">{data.agency.name}</h2><p>Buyer: {data.sale.customerName}</p><p>Sale: {data.sale.documentNumber}</p>{data.sale.vin&&<p>VIN / chassis: {data.sale.vin}</p>}{data.sale.photos?.[0]&&<img className="my-3 aspect-[4/3] max-h-64 w-full rounded-lg object-contain" src={data.sale.photos[0]} alt={data.sale.title}/>}<p>Status: {data.sale.status}</p><div className="my-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><p>Agreed price<br/><strong>{money(data.sale.agreedPriceCents)}</strong></p><p>Confirmed payments<br/><strong>{money(data.sale.paidCents)}</strong></p><p>Balance<br/><strong>{money(data.sale.agreedPriceCents-data.sale.paidCents)}</strong></p></div><p className="whitespace-pre-wrap break-words">{data.sale.terms}</p><p className="mt-3">{data.sale.status==='delivered'?'Vehicle handover completed':data.sale.status==='cancelled'?'Reservation cancelled':data.sale.paidCents===data.sale.agreedPriceCents?'Payment complete. Arrange collection with your dealer.':'Next: complete the agreed payments before collection.'}</p><a className="btn-ghost mt-3" href={`https://wa.me/${data.agency.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(`Regarding my purchase ${data.sale.documentNumber}: ${window.location.href}`)}`} target="_blank" rel="noreferrer">Contact dealer on WhatsApp</a></Card>
    {staff&&<Card><h2 className="text-lg font-semibold">Issue sales documents</h2><div className="mt-3 grid gap-2 sm:grid-cols-3"><Button loading={busy} onClick={()=>issue('sale')}>Issue sale agreement</Button><Button loading={busy} onClick={()=>issue('statement')}>Issue balance statement</Button><Button loading={busy} disabled={data.sale.status!=='delivered'} onClick={()=>issue('handover')}>Issue handover record</Button></div></Card>}
    {claims.appRole==='admin'&&<Card><h2 className="font-semibold">Give the buyer private portal access</h2><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);const r=await dealerCall<{token:string}>('createInvitation',{email:f.get('email'),role:'customer',customerId:data.sale.customerId});setInvite(`${location.origin}/invite/${r.token}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Input name="email" type="email" required aria-label="Buyer invitation email" placeholder="Buyer email"/><Button loading={busy}>Create buyer invitation</Button></form>{invite&&<Input aria-label="Buyer invitation link" readOnly value={invite}/>}<p className="mt-2 text-sm">Share the invitation privately. Buyers with an existing account already have access to their purchase.</p><Link className="mt-3 inline-block underline" to="/app/invitations">Manage invitations</Link></Card>}
    <Card><h2 className="mb-3 text-lg font-semibold">Payment and handover history</h2>{data.entries.sort((a,b)=>a.date.localeCompare(b.date)).map(e=><div key={e.id} className="border-b py-3"><p>{e.action} · {money(e.amountCents)} · {new Date(e.date).toLocaleString()}</p><p className="break-words">{e.evidence}</p>{staff&&['payment','refund'].includes(e.action)&&<Button variant="ghost" loading={busy} onClick={()=>issue('receipt',e.id)}>Issue {e.action==='refund'?'refund record':'payment receipt'}</Button>}</div>)}</Card>
    <Card><h2 className="mb-3 text-lg font-semibold">Your documents</h2>{data.documents.length===0&&<p>No documents issued yet.</p>}{data.documents.map(d=><Button key={d.id} variant="ghost" className="mb-2" onClick={()=>setSheet(d)}>{d.kind} · {d.number}</Button>)}</Card>
  </>}{sheet&&createPortal(<div className="print-overlay fixed inset-0 z-[100] overflow-auto bg-white p-5 text-black"><section className="print-sheet mx-auto max-w-2xl break-words"><div className="no-print mb-6 flex gap-3"><Button onClick={()=>window.print()}>Print / save PDF</Button><Button variant="ghost" onClick={()=>setSheet(undefined)}>Close document</Button></div><h1 className="text-2xl font-bold">{sheet.agency}</h1><h2 className="my-4 text-xl">{sheet.kind==='sale'?'Vehicle sale agreement':sheet.kind==='statement'?'Balance statement':sheet.kind==='handover'?'Vehicle handover record':sheet.entry?.action==='refund'?'Refund confirmation':'Payment receipt'}</h2><p>Document: {sheet.number}</p><p>Issued: {new Date(sheet.issuedAt).toLocaleString()}</p><p>Sale: {sheet.saleReference}</p><p>Buyer: {sheet.customer}</p><p>Vehicle: {sheet.title}</p>{sheet.vin&&<p>VIN / chassis: {sheet.vin}</p>}{sheet.customerPhone&&<p>Buyer phone: {sheet.customerPhone}</p>}{sheet.agencyWhatsapp&&<p>Dealer contact: {sheet.agencyWhatsapp}</p>}{sheet.handoverEvidence&&<p className="mt-4">Handover acknowledgement: {sheet.handoverEvidence}</p>}{sheet.entry?<><p className="my-4 text-xl">{sheet.entry.action}: {money(sheet.entry.amountCents)}</p><p>Reference: {sheet.entry.evidence}</p></>:<><p className="mt-4">Agreed price: {money(sheet.agreedPriceCents)}</p><p>Confirmed payments: {money(sheet.paidCents)}</p><p>Outstanding balance at issue: {money(sheet.balanceCents)}</p><p>Status at issue: {sheet.status}</p></>}<p className="my-4 whitespace-pre-wrap">Terms: {sheet.terms}</p><p className="text-sm">This document records the transaction at its issue date. Later corrections remain in the transaction history.</p></section></div>,document.body)}</div>;
}

