import { useEffect, useState, type FormEvent } from 'react';
import { useParams, Link } from 'react-router-dom';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../lib/firebase';
import Brand from '../components/Brand';
import PublicStockBrowser, { type PublicStock } from '../components/PublicStockBrowser';
import { StockSpecList } from '../components/StockSpecifications';
import { Button, Input, Select, TextArea } from '../components/ui';
import Seo from '../components/Seo';
import '../marketing.css';
type ShowroomData={ acceptsEnquiries?:boolean; name:string; whatsapp:string; limited?:boolean; stock:(PublicStock & { description:string })[] };
export default function Showroom() {
 const {slug,stockId}=useParams();const [data,setData]=useState<ShowroomData>(),[error,setError]=useState(''),[photo,setPhoto]=useState(0),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(undefined);setError('');void httpsCallable(functions,'dealerShowroom')({slug}).then(r=>{if(active)setData(r.data as ShowroomData);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[slug,retry]);
 useEffect(()=>{setPhoto(0);},[stockId]);const selected=data?.stock.find(s=>s.id===stockId);
 const whatsapp=(s?:PublicStock)=>`https://wa.me/${data?.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(s?`I'm interested in ${s.title}, stock ${s.id}. ${window.location.href}`:'Please tell me about your current stock and sourcing services.')}`;
 return <div className="marketing-page automotive-landing showroom-page"><Seo title={data ? `${data.name} — dealer showroom | Radbit Auto` : 'Dealer showroom | Radbit Auto'} description={data ? `Browse local stock and sourcing enquiries from ${data.name} on Radbit Auto. Prices in USD.` : 'Browse local stock or ask a dealer to source a vehicle on Radbit Auto. Prices in USD.'} path={`/showroom/${slug ?? ''}`} jsonLd={data ? { '@context': 'https://schema.org', '@type': 'AutoDealer', name: data.name, url: `https://auto.radbitstudios.co.zw/showroom/${slug}` } : undefined} /><header className="marketing-header"><Link className="product-wordmark" to="/"><Brand/></Link><nav><Link to="/#cars">All cars</Link><Link to="/login">Sign in</Link></nav></header><main><section className="marketing-section"><p className="interface-eyebrow">Independent dealer showroom</p><h1>{data?.name??'Dealer showroom'}</h1><p>Browse local stock or ask the dealer to source a vehicle. Prices are in USD.</p></section>
 {error?<section className="catalogue-empty" role="alert"><p>{error}</p><Button onClick={()=>setRetry(n=>n+1)}>Try again</Button></section>:!data?<p role="status">Loading showroom…</p>:<>
 {stockId?<section className="marketing-section">{selected?<><Link to={`/showroom/${slug}`}>← All vehicles from {data.name}</Link><div className="vehicle-detail-grid"><div>{selected.photos[photo]?<img className="vehicle-main-photo" src={selected.photos[photo]} alt={`${selected.title}, photo ${photo+1}`} referrerPolicy="no-referrer"/>:<div className="catalogue-photo-empty">Vehicle photo pending</div>}<div className="vehicle-thumbnails">{selected.photos.map((src,i)=><button key={`${src}-${i}`} aria-label={`View photo ${i+1}`} aria-pressed={i===photo} onClick={()=>setPhoto(i)}><img src={src} alt="" loading="lazy" referrerPolicy="no-referrer"/></button>)}</div></div><div><p className="interface-eyebrow">Local stock · {selected.location||'Confirm location with dealer'}</p><h2>{selected.title}</h2><p className="catalogue-price">USD {(selected.askingPriceCents/100).toLocaleString('en-US',{minimumFractionDigits:2})}</p><p className="interface-note">Dealer asking price. Confirm availability, condition, registration, transfer fees and what is included before paying.</p><StockSpecList specs={selected.specs}/><p className="vehicle-description">{selected.description||'Ask the dealer for condition and viewing details.'}</p><p className="interface-note">Stock reference: {selected.id}</p><div className="stock-card-actions"><a className="btn-primary" href={whatsapp(selected)} target="_blank" rel="noreferrer">Ask on WhatsApp</a><a className="btn-ghost" href="#vehicle-enquiry">Send an enquiry</a><a className="btn-ghost" href={`https://wa.me/?text=${encodeURIComponent(`${selected.title} · USD ${(selected.askingPriceCents/100).toLocaleString()} · ${window.location.href}`)}`} target="_blank" rel="noreferrer">Share vehicle</a></div></div></div></>:<div className="catalogue-empty"><h2>This vehicle is no longer listed.</h2><p>It may be reserved, sold or withdrawn. Browse current stock or contact the dealer for alternatives.</p><Link className="btn-primary" to={`/showroom/${slug}`}>Browse current stock</Link></div>}</section>:<section className="marketing-section"><PublicStockBrowser stock={data.stock.map(s=>({...s,dealerName:data.name,slug:slug!}))} limited={data.limited}/></section>}
 {data.acceptsEnquiries!==false&&(!stockId||selected)?<Enquiry key={stockId??slug} slug={slug!} dealer={data.name} selected={selected}/>:<section className="catalogue-empty"><p>Contact this dealer directly to confirm current stock and sourcing availability.</p><a className="btn-ghost" href={whatsapp()}>Contact dealer on WhatsApp</a></section>}
 </>}
 </main><footer className="marketing-footer"><Brand/><Link to="/help">Support &amp; privacy</Link><Link to="/#dealers">Run your dealership with Radbit Auto</Link></footer></div>;
}
function Enquiry({slug,dealer,selected}:{slug:string;dealer:string;selected?:PublicStock}) {
 const [sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await httpsCallable(functions,'enquireDealerShowroom')({...Object.fromEntries(f),slug,...(selected?{stockId:selected.id,interest:'stock'}:{}),budgetCents:Math.round(Number(f.get('budget')||0)*100)});setSent(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section id="vehicle-enquiry" className="marketing-section showroom-enquiry"><div><p className="interface-eyebrow">Speak to {dealer}</p><h2>{selected?'Enquire about this vehicle':'Tell us what you’re looking for'}</h2><p>{selected?`${selected.title} · Your enquiry includes this stock reference.`:'Choose local stock or sourcing. Your request goes directly to this dealer.'}</p><p className="interface-note">An enquiry does not reserve a car or collect payment.</p></div><div>{sent?<p role="status">Your enquiry has reached {dealer}. The dealer will contact you.</p>:<form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><label>Your name<Input name="name" required autoComplete="name" aria-label="Your name" maxLength={150}/></label><label>WhatsApp / phone<Input name="phone" type="tel" required autoComplete="tel" aria-label="WhatsApp / phone" maxLength={50}/></label>{!selected&&<label>Interest<Select name="interest" aria-label="Interest"><option value="stock">Local stock</option><option value="import">Import on my behalf</option><option value="either">Either</option></Select></label>}<label>Budget (USD, optional)<Input name="budget" aria-label="Budget in USD" type="number" min="0" max="100000000" step="0.01"/></label><label className="sm:col-span-2">{selected?'Questions or viewing request':'Vehicle and budget'}<TextArea name="preferences" required aria-label="Vehicle and budget" defaultValue={selected?`I would like to view ${selected.title}. Please confirm availability and what is included in the price.`:''} maxLength={1500}/></label><Button loading={busy}>Send enquiry</Button>{error&&<p className="sm:col-span-2" role="alert">{error}</p>}</form>}</div></section>;
}
