import { useEffect, useState, type FormEvent } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../lib/firebase';
import { Button, Input, Select } from './ui';
export type NextAction={title:string;responsible:string;dueDate:string;state:string};
export default function CaseNextAction({caseId,action,staff}:{caseId:string;action?:NextAction;staff:boolean}){
 const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[responsible,setResponsible]=useState('agency'),[dueDate,setDueDate]=useState(''),[state,setState]=useState('pending'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setTitle(action?.title??'');setResponsible(action?.responsible??'agency');setDueDate(action?.dueDate??'');setState(action?.state??'pending');},[caseId,action]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await httpsCallable(functions,'setCaseNextAction')({caseId,title,responsible,dueDate,state});setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="case-passport mb-3" aria-label="Next action"><p className="interface-eyebrow">Next action</p>{action?<><h2 className="mt-2 font-semibold">{action.title}</h2><p className="mt-2 text-sm">{action.state==='complete'?'Completed':action.responsible==='customer'?'Action needed from the customer':'Your agency is handling this'}{action.dueDate?` · Target date: ${action.dueDate}`:''}</p>{action.dueDate&&<p className="mt-2 text-xs text-slate-400">An agency action target, not a confirmed vessel or delivery date.</p>}</>:<p className="mt-2 text-sm text-slate-300">Your agency has not recorded a specific next action yet. Check the timeline or contact the agency.</p>}{staff&&<><Button variant="ghost" className="mt-3" onClick={()=>setOpen(!open)}>{action?'Update next action':'Set next action'}</Button>{open&&<form className="mt-3 grid gap-3" onSubmit={submit}><label>Action needed<Input required aria-label="Action needed" value={title} onChange={e=>setTitle(e.target.value)} maxLength={300}/></label><label>Who needs to act?<Select aria-label="Who needs to act?" value={responsible} onChange={e=>setResponsible(e.target.value)}><option value="agency">Our agency</option><option value="customer">Customer</option></Select></label><label>Target date (optional)<Input aria-label="Next action target date" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Status<Select aria-label="Next action status" value={state} onChange={e=>setState(e.target.value)}><option value="pending">Pending</option><option value="complete">Completed</option></Select></label><Button loading={busy}>Save next action</Button>{error&&<p role="alert">{error}</p>}</form>}</>}</section>;
}
