import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { dealerCall,dealerMoney as money } from '../lib/dealer';
import { useAuth } from '../lib/auth';
type Data={dealer_leads:{status:string;followUp:string}[];dealer_stock:{status:string}[];dealer_sales:{stockId:string;status:string;agreedPriceCents:number;paidCents:number}[];dealer_costs?:{id:string;complete:boolean;acquisitionCents:number;directCostsCents:number}[];dealer_acquisitions:{stage:string}[]};
export default function DealerOverview(){
  const {claims}=useAuth();const [data,setData]=useState<Data>();const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;dealerCall<Data>('dealershipWorkspace',{}).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[claims.companyId,refresh]);
  const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const leads=data?.dealer_leads.filter(l=>!['won','lost'].includes(l.status))??[];const due=leads.filter(l=>l.followUp&&l.followUp<=today).length;
  const delivered=data?.dealer_sales.filter(s=>s.status==='delivered')??[];const complete=delivered.filter(s=>data?.dealer_costs?.some(c=>c.id===s.stockId&&c.complete));const margin=complete.reduce((n,s)=>{const cost=data!.dealer_costs!.find(c=>c.id===s.stockId)!;return n+s.agreedPriceCents-cost.acquisitionCents-cost.directCostsCents;},0);
  return <section className="dashboard-section my-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2>Sales and stock</h2><button className="text-sm underline" onClick={()=>setRefresh(n=>n+1)}>Refresh dealer summary</button></div>{error?<p role="alert">{error}</p>:!data?<p>Loading dealer activity…</p>:<><div className="my-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><p>Open enquiries<br/><strong className="text-xl">{leads.length}</strong></p><p>Follow-ups due<br/><strong className="text-xl">{due}</strong></p><p>Available stock<br/><strong className="text-xl">{data.dealer_stock.filter(s=>s.status==='available').length}</strong></p><p>Reserved sales<br/><strong className="text-xl">{data.dealer_sales.filter(s=>s.status==='reserved').length}</strong></p></div>{claims.appRole==='admin'&&<p className="mb-3 text-sm">Active dealer acquisitions: {data.dealer_acquisitions.filter(a=>a.stage!=='stocked').length}. Recorded margin from {complete.length} complete-cost delivered sales: <strong>{money(margin)}</strong>. {delivered.length-complete.length} delivered sales have incomplete costs. Excludes overheads.</p>}<Link className="btn-ghost" to="/app/dealership">Open dealership</Link></>}</section>;
}
