import { useState } from 'react';
import { createPortal } from 'react-dom';
import { api } from '../lib/api';
import { useAuth } from '../lib/auth';
import { usd, dateTime } from '../lib/format';
import type { QuotationDoc, PaymentDocLite } from '../lib/types';
import { Button, Card, Input, Select } from './ui';

export function FinancialDocuments({ caseNum, agency, customer, quote, payments }: { caseNum: string; agency: string; customer: string; quote?: Pick<QuotationDoc, 'terms' | 'version' | 'totalDueCents' | 'totalPaidCents' | 'purchasePriceCents' | 'charges' | 'taxTotalCents' | 'acceptedBy'> & { id: string }; payments: PaymentDocLite[] }) {
  const { claims } = useAuth();
  const [sheet, setSheet] = useState<'quote' | PaymentDocLite | null>(null);
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function accept() { if (!quote) return; setBusy(true); try { await api.acceptQuotation({ quotationId: quote.id }); setMessage('Quotation accepted.'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  const receipt = sheet && sheet !== 'quote' ? sheet : null;
  return <Card className="mb-3"><h2 className="section-title">Quotations and receipts</h2>
    {quote ? <><Button variant="ghost" onClick={() => setSheet('quote')}>Print quotation / save PDF</Button>{claims.appRole === 'customer' ? <Button onClick={accept} loading={busy} disabled={Boolean(quote.acceptedBy)}>{quote.acceptedBy ? 'Quotation accepted' : 'Accept this quotation'}</Button> : null}</> : <p>No issued quotation yet.</p>}
    {payments.filter((p) => p.status === 'confirmed').map((p) => <Button key={p.id} variant="ghost" className="mt-2" onClick={() => setSheet(p)}>Receipt {p.providerRef || p.id.slice(0, 8)} · {usd(p.amountCents)}</Button>)}
    {message ? <p role="status">{message}</p> : null}
    {sheet ? createPortal(<div className="print-overlay fixed inset-0 z-[100] overflow-auto bg-white p-6 text-black"><section className="print-sheet mx-auto max-w-2xl"><div className="no-print mb-6 flex gap-3"><button className="rounded border px-4 py-2" onClick={() => window.print()}>Print / save PDF</button><button className="rounded border px-4 py-2" onClick={() => setSheet(null)}>Close document</button></div><h1 className="text-2xl font-bold">{agency}</h1><h2 className="my-4 text-xl">{receipt ? (receipt.recipient === 'supplier' ? 'Supplier payment confirmation' : 'Payment receipt') : `Quotation · version ${quote?.version}`}</h2><p>Case: {caseNum}</p><p>Customer: {customer}</p>{receipt ? <><p>Receipt: {receipt.id}</p><p>Payment date: {dateTime(receipt.createdAt)}</p><p>Method: {receipt.method}</p><p>Reference: {receipt.providerRef ?? 'Cash / internal reference'}</p><p className="my-6 text-xl">Confirmed USD payment: {usd(receipt.amountCents)}</p><p>Recipient: {receipt.recipient === 'supplier' ? 'Supplier paid directly by customer' : 'Agency'}. Later corrections remain in the case ledger.</p></> : <><p>Quotation reference: {quote?.id}</p><p>Route: {quote?.terms?.route||'Confirm with agency'}</p><p>Included services: {quote?.terms?.inclusions||'Confirm service scope with agency'}</p><p>Excluded costs: {quote?.terms?.exclusions||'Not specified; confirm before agreeing'}</p><p>Price valid through: {quote?.terms?.validUntil||'Reconfirm before paying'}</p><dl className="my-6 space-y-2"><div className="flex justify-between"><dt>Vehicle invoice</dt><dd>{quote?.purchasePriceCents === undefined ? 'Not recorded in this quotation version' : usd(quote.purchasePriceCents)}</dd></div>{Object.entries(quote?.charges ?? {}).map(([key, value]) => <div key={key} className="flex justify-between"><dt>{({ freightCents: 'Sea freight', insuranceCents: 'Insurance', borderFreightCents: 'Transport to Zimbabwe border', portChargesCents: 'Port charges', localDeliveryCents: 'Local delivery', agencyFeeCents: 'Agency service fee' } as Record<string, string>)[key]}</dt><dd>{usd(value)}</dd></div>)}<div className="flex justify-between"><dt>Estimated taxes</dt><dd>{quote?.taxTotalCents === undefined ? 'Breakdown unavailable for this version' : usd(quote.taxTotalCents)}</dd></div><div className="flex justify-between font-bold"><dt>Total USD</dt><dd>{usd(quote?.totalDueCents ?? 0)}</dd></div><div className="flex justify-between"><dt>Confirmed payments</dt><dd>{usd(quote?.totalPaidCents ?? 0)}</dd></div></dl><p>Import taxes are an estimate subject to final customs assessment. Agency staff should verify the applicable rates before you pay. This is not a customs assessment or tax invoice.</p><p className="mt-4">Changes require a new quotation version. Accepting a quotation does not authorize an automatic payment.</p></>}</section></div>, document.body) : null}
  </Card>;
}

export function PaymentCorrection({ paymentId, onCorrected }: { paymentId: string; onCorrected: (status: string) => void }) {
  const { claims } = useAuth(); const [open, setOpen] = useState(false);
  const [action, setAction] = useState<'reverse' | 'refund'>('reverse');
  const [reason, setReason] = useState(''); const [reference, setReference] = useState('');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  if (claims.appRole !== 'admin') return null;
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await api.correctPayment({ paymentId, action, reason, reference }); onCorrected(action === 'refund' ? 'refunded' : 'reversed'); setOpen(false); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  return <div className="mt-3"><Button variant="ghost" onClick={() => setOpen(!open)}>Correct this payment</Button>{open ? <form onSubmit={submit} className="mt-3 space-y-3"><p className="text-sm">Full payment correction. Refunds must already have been sent outside this portal. The original payment stays in the audit trail and the case balance is recalculated.</p><Select aria-label="Correction action" value={action} onChange={(e) => setAction(e.target.value as typeof action)}><option value="reverse">Reverse an incorrect entry</option><option value="refund">Record a completed refund</option></Select><Input aria-label="Correction reason" required minLength={5} maxLength={500} placeholder="Reason for correction" value={reason} onChange={(e) => setReason(e.target.value)} /><Input aria-label="Correction reference" required maxLength={150} placeholder="Refund transaction or correction reference" value={reference} onChange={(e) => setReference(e.target.value)} /><Button type="submit" loading={busy}>Record correction</Button>{message ? <p role="alert">{message}</p> : null}</form> : null}</div>;
}

