import { useEffect,useState } from 'react';
import { dealerCall,dealerCents,dealerMoney as money } from '../lib/dealer';
import { Button,Card,Input,Select } from './ui';
type Result={cases:{id:string;caseNum:string;stage:string}[];events:{id:string;caseId:string;kind:string;amountCents:number;evidence:string;reversedBy?:string}[]};
export default function ImportDealResults(){
  const [data,setData]=useState<Result>({cases:[],events:[]});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setData(await dealerCall<Result>('importDealResults',{}));}useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
  const fees=data.events.filter(e=>e.kind==='fee_earned').reduce((n,e)=>n+e.amountCents,0);const costs=data.events.filter(e=>e.kind==='dealer_expense').reduce((n,e)=>n+e.amountCents,0);
  return <Card><h2 className="text-xl font-semibold">Customer import earnings</h2><p className="mt-2">Earned fees / commissions {money(fees)} · Dealer-borne costs {money(costs)} · Recorded deal result {money(fees-costs)}</p><p className="mt-2 text-sm">Record fees actually earned and expenses borne by your business. Customer vehicle costs and funds forwarded to suppliers are separate. Results exclude overheads and unrecorded expenses.</p>{error&&<p role="alert">{error}</p>}
    <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;form.dataset.requestId??=crypto.randomUUID();setBusy(true);setError('');try{const f=new FormData(form);await dealerCall('recordImportDealResult',{...Object.fromEntries(f),amountCents:dealerCents(f.get('amount')),requestId:form.dataset.requestId});await load();form.reset();delete form.dataset.requestId;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Import case<Select required name="caseId" aria-label="Earnings import case"><option value="">Choose case</option>{data.cases.map(c=><option key={c.id} value={c.id}>{c.caseNum} · {c.stage}</option>)}</Select></label><label>Record as<Select name="kind" aria-label="Import earnings event"><option value="fee_earned">Service fee / commission earned</option><option value="dealer_expense">Expense borne by dealer</option></Select></label><label>Actual USD amount<Input required type="number" min="0.01" step="0.01" name="amount" aria-label="Import earnings amount"/></label><label>Evidence / reference<Input required name="evidence" aria-label="Import earnings evidence"/></label><Button loading={busy}>Record import deal result</Button></form>
    {data.events.map(e=><div key={e.id} className="mt-4 border-t pt-3"><p className="break-words">{data.cases.find(c=>c.id===e.caseId)?.caseNum} · {e.kind.replaceAll('_',' ')} · {money(e.amountCents)} · {e.evidence}</p>{!e.reversedBy&&e.amountCents>0&&<form className="mt-2 flex flex-col gap-2 sm:flex-row" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{const f=new FormData(event.currentTarget);await dealerCall('recordImportDealResult',{caseId:e.caseId,kind:'reverse',entryId:e.id,evidence:f.get('evidence'),requestId:crypto.randomUUID()});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Input name="evidence" required aria-label="Reversal reason" placeholder="Correction reason / reference"/><Button disabled={busy} variant="ghost">Reverse entry</Button></form>}</div>)}
  </Card>;
}
