import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { StockSpecList, stockChoices, type StockSpecs } from './StockSpecifications';
import { landedRange, type SupplierLandedEstimate } from '../lib/zimbabweImport';
export type PublicStock = { id:string; title:string; location:string; askingPriceCents:number; photos:string[]; dealerName:string; slug:string; specs?:StockSpecs; source?:'beforward'; checkedAt?:string; estimate?:SupplierLandedEstimate|null };
const vehicleLink = (s:PublicStock) => s.source==='beforward'?`/imports/${s.id}`:`/showroom/${s.slug}/vehicle/${s.id}`;
const key = 'radbit:auto:shortlist:v1';
function savedIds(): string[] { try { const value=JSON.parse(localStorage.getItem(key) ?? '[]'); return Array.isArray(value)?value.filter(v=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(v)).slice(0,3):[]; } catch { return []; } }
export default function PublicStockBrowser({ stock, limited=false }: { stock:PublicStock[]; limited?:boolean }) {
  const [query,setQuery]=useState(''),[budget,setBudget]=useState(''),[year,setYear]=useState(''),[fuel,setFuel]=useState(''),[transmission,setTransmission]=useState(''),[body,setBody]=useState(''),[order,setOrder]=useState(''),[saved,setSaved]=useState(savedIds),[message,setMessage]=useState(''),[limit,setLimit]=useState(60);
  useEffect(()=>{setLimit(60);},[query,budget,year,fuel,transmission,body,order]);
  const selected=stock.filter(s=>saved.includes(s.id));
  const matches=stock.filter(s=>`${s.title} ${s.location} ${s.dealerName} ${s.specs?.make??''} ${s.specs?.model??''}`.toLowerCase().includes(query.toLowerCase().trim())&&(!budget||s.askingPriceCents<=Number(budget)*100)&&(!year||(s.specs?.year??0)>=Number(year))&&(!fuel||s.specs?.fuel===fuel)&&(!transmission||s.specs?.transmission===transmission)&&(!body||s.specs?.bodyType===body)).sort((a,b)=>order==='low'?a.askingPriceCents-b.askingPriceCents:order==='high'?b.askingPriceCents-a.askingPriceCents:order==='year'?(b.specs?.year??0)-(a.specs?.year??0):0);
  function toggle(id:string) { if(!saved.includes(id)&&saved.length>=3){setMessage('Compare up to three vehicles. Remove one to add another.');return;} const next=saved.includes(id)?saved.filter(v=>v!==id):[...saved,id];setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setMessage('');}catch{setMessage('Your shortlist is available for this visit. Browser storage is unavailable.');} }
  function clear(){setQuery('');setBudget('');setYear('');setFuel('');setTransmission('');setBody('');}
  return <>
    <div className="catalogue-filters"><label>Make, model, location or dealer<input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Toyota Aqua, Harare" /></label><label>{stock.some(s=>s.source==='beforward')?'Maximum supplier vehicle price (USD)':'Maximum price (USD)'}<select className="field" aria-label={stock.some(s=>s.source==='beforward')?'Maximum supplier vehicle price (USD)':'Maximum price (USD)'} value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Any budget</option>{[5000,10000,15000,20000,30000].map(n=><option key={n} value={n}>Up to ${n.toLocaleString()}</option>)}</select></label></div>
    <details className="stock-filter-details"><summary>More filters &amp; sort</summary><div className="stock-more-filters"><label>Year from<input className="field" aria-label="Year from" type="number" min="1960" max={new Date().getFullYear()+1} value={year} onChange={e=>setYear(e.target.value)} /></label>{([['Fuel',fuel,setFuel,stockChoices.fuel],['Transmission',transmission,setTransmission,stockChoices.transmission],['Body type',body,setBody,stockChoices.bodyType]] as const).map(([label,value,set,options])=><label key={label}>{label}<select className="field" aria-label={label} value={value} onChange={e=>set(e.target.value)}><option value="">Any</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>)}<label>Sort by<select className="field" aria-label="Sort by" value={order} onChange={e=>setOrder(e.target.value)}><option value="">Dealer listing order</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="year">Newest year</option></select></label></div></details>
    <p className="interface-note my-4" role="status">{matches.length} {matches.length===1?'vehicle':'vehicles'} matching your search{limited?' in this selection':''}.</p>
    {saved.length>0&&<section className="stock-comparison" aria-label="Saved vehicle comparison"><div className="catalogue-heading"><h3>Your shortlist</h3><button className="btn-ghost" onClick={()=>{setSaved([]);try{localStorage.removeItem(key);}catch{}}}>Clear shortlist</button></div><p className="interface-note">Saved on this device. Availability and prices must be confirmed with the dealer.</p>{saved.length>selected.length&&<p>Some saved vehicles are no longer listed in this selection.</p>}<div className="stock-compare-grid">{selected.map(s=><article key={s.id}><h4>{s.title}</h4><p>USD {(s.askingPriceCents/100).toLocaleString()}</p><StockSpecList specs={s.specs}/><Link className="btn-ghost" to={vehicleLink(s)}>View vehicle</Link><button className="btn-ghost" onClick={()=>toggle(s.id)}>Remove<span className="sr-only"> {s.title}</span></button></article>)}</div></section>}
    {message&&<p role="status">{message}</p>}
    <div className="catalogue-grid">{matches.slice(0,limit).map(s=><article className="catalogue-car" key={s.id}>{s.photos[0]?<img src={s.photos[0]} alt={s.title} loading="lazy" referrerPolicy="no-referrer"/>:<div className="catalogue-photo-empty">Vehicle photo pending</div>}<div className="catalogue-car-body"><p className="interface-eyebrow">{s.location||'Confirm vehicle location'} · {s.source==='beforward'?'Available to import':'Local stock'}</p><h3>{s.title}</h3><p className="catalogue-price">USD {(s.askingPriceCents/100).toLocaleString('en-US',{minimumFractionDigits:2})}</p>{s.estimate&&<p className="text-sm">Est. landed in Zimbabwe: {landedRange(s.estimate)} (estimate)</p>}<p className="text-sm mb-3">{[s.specs?.year,s.specs?.mileageKm===undefined?null:`${s.specs.mileageKm.toLocaleString()} km`,s.specs?.fuel,s.specs?.transmission].filter(v=>v!==undefined&&v!==null).join(' · ')||'Ask dealer for specifications'}</p><p className="text-sm mb-4">{s.source==='beforward'?'BE FORWARD vehicle price. Shipping, duties and dealer fees are additional.':`Offered by ${s.dealerName}`}</p>{s.checkedAt&&<p className="interface-note mb-3">Listed when checked {new Date(s.checkedAt).toLocaleDateString()}. Dealer confirms current availability.</p>}<div className="stock-card-actions"><Link className="btn-ghost" to={vehicleLink(s)}>{s.source==='beforward'?'View car & choose a dealer':'View vehicle & enquire'}<span className="sr-only"> about {s.title}</span></Link><button className="stock-save" aria-pressed={saved.includes(s.id)} onClick={()=>toggle(s.id)}>{saved.includes(s.id)?'Saved':'Shortlist'}<span className="sr-only"> {s.title}</span></button></div></div></article>)}</div>
    {matches.length>limit&&<div className="catalogue-more"><button className="btn-ghost" onClick={()=>setLimit(n=>n+60)}>Show more vehicles ({matches.length-limit} remaining in this selection)</button></div>}
    {!matches.length&&<div className="catalogue-empty"><h3>{stock.length?'No cars match those filters.':'The next listings are on their way.'}</h3><p>{stock.length?'Try another model or a higher budget. You can also ask a participating dealer to source a car.':'There are no published vehicles here yet. Browse cars to import, or find a dealer who can source one for you.'}</p>{stock.length>0?<button className="btn-ghost mt-4" onClick={clear}>Clear filters</button>:<div className="stock-card-actions mt-4"><Link className="btn-primary" to="/imports">Browse import cars</Link><Link className="btn-ghost" to="/#sourcing">Find a dealer</Link></div>}</div>}
  </>;
}
