import { useState } from 'react';
import { ref, uploadBytes } from 'firebase/storage';
import { storage } from '../lib/firebaseData';
import { dealerCall } from '../lib/dealer';
import { Button } from './ui';
import { optimizeStockImage } from '../lib/stockImage';
export default function StockPhotos({companyId,stockId,photos,refresh,description,published}:{companyId:string;stockId:string;photos:string[];refresh:()=>Promise<void>;description:string;published:boolean}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function arrange(next:string[]){setBusy(true);setError('');try{await dealerCall('publishDealerStock',{stockId,photos:next,description,published});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="mt-4 space-y-3"><p className="font-semibold">Vehicle photos</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{photos.map((p,i)=><div key={p} className="space-y-1"><img src={p} alt={`Vehicle photo ${i+1}`} className="aspect-[4/3] w-full rounded-lg object-cover"/>{i===0?<p className="text-xs">Cover photo</p>:<Button variant="ghost" disabled={busy} onClick={()=>arrange([p,...photos.filter(v=>v!==p)])}>Make cover</Button>}<Button variant="ghost" disabled={busy} onClick={()=>arrange(photos.filter(v=>v!==p))}>Remove photo</Button></div>)}</div><label className="block">Upload from phone or camera<input className="field mt-1" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||photos.length>=8} aria-label={`Upload photos for ${stockId}`} onChange={async e=>{const files=Array.from(e.target.files??[]);setBusy(true);setError('');try{if(files.length+photos.length>8)throw new Error('Maximum eight photos per vehicle');for(const file of files){const optimized=await optimizeStockImage(file);const path=`stock-photos/${companyId}/${stockId}/${crypto.randomUUID()}`;await uploadBytes(ref(storage,path),optimized,{contentType:optimized.type});await dealerCall('attachDealerStockPhoto',{stockId,path});}await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{busy&&<p role="status">Optimizing and uploading photos…</p>}{error&&<p role="alert">{error}</p>}<p className="text-xs">Photos are resized to at most 1920 pixels and compressed before upload (under 2 MB). Uploaded vehicle photos can be shared publicly. Keep personal documents in the private import document area.</p></div>;
}
